var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.checkStringArgs=function(e,p,y){if(null==e)throw new TypeError("The 'this' value for String.prototype."+y+" must not be null or undefined");if(p instanceof RegExp)throw new TypeError("First argument to String.prototype."+y+" must not be a regular expression");return e+""};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(e,p,y){e!=Array.prototype&&e!=Object.prototype&&(e[p]=y.value)};$jscomp.getGlobal=function(e){return"undefined"!=typeof window&&window===e?e:"undefined"!=typeof global&&null!=global?global:e};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(e,p,y,D){if(p){y=$jscomp.global;e=e.split(".");for(D=0;D<e.length-1;D++){var H=e[D];H in y||(y[H]={});y=y[H]}e=e[e.length-1];D=y[e];p=p(D);p!=D&&null!=p&&$jscomp.defineProperty(y,e,{configurable:!0,writable:!0,value:p})}};
$jscomp.polyfill("String.prototype.endsWith",function(e){return e?e:function(e,y){var p=$jscomp.checkStringArgs(this,e,"endsWith");e+="";void 0===y&&(y=p.length);y=Math.max(0,Math.min(y|0,p.length));for(var H=e.length;0<H&&0<y;)if(p[--y]!=e[--H])return!1;return 0>=H}},"es6","es3");
$jscomp.polyfill("String.prototype.startsWith",function(e){return e?e:function(e,y){var p=$jscomp.checkStringArgs(this,e,"startsWith");e+="";var H=p.length,la=e.length;y=Math.max(0,Math.min(y|0,p.length));for(var Z=0;Z<la&&y<H;)if(p[y++]!=e[Z++])return!1;return Z>=la}},"es6","es3");
$jscomp.polyfill("String.prototype.repeat",function(e){return e?e:function(e){var p=$jscomp.checkStringArgs(this,null,"repeat");if(0>e||1342177279<e)throw new RangeError("Invalid count value");e|=0;for(var D="";e;)if(e&1&&(D+=p),e>>>=1)p+=p;return D}},"es6","es3");
(function(){function e(a){function b(b){return function(c){return a(b,c)}}b.arity=2;b.func=a;return b}function p(a){function b(b){return function(c){return function(d){return a(b,c,d)}}}b.arity=3;b.func=a;return b}function y(a){function b(b){return function(c){return function(d){return function(h){return a(b,c,d,h)}}}}b.arity=4;b.func=a;return b}function D(a){function b(b){return function(c){return function(d){return function(h){return function(q){return a(b,c,d,h,q)}}}}}b.arity=5;b.func=a;return b}
function H(a){function b(b){return function(c){return function(d){return function(h){return function(q){return function(t){return a(b,c,d,h,q,t)}}}}}}b.arity=6;b.func=a;return b}function la(a){function b(b){return function(c){return function(d){return function(h){return function(q){return function(t){return function(e){return a(b,c,d,h,q,t,e)}}}}}}}b.arity=7;b.func=a;return b}function Z(a){function b(b){return function(c){return function(d){return function(h){return function(q){return function(t){return function(e){return function(l){return a(b,
c,d,h,q,t,e,l)}}}}}}}}b.arity=8;b.func=a;return b}function sb(a){function b(b){return function(c){return function(d){return function(h){return function(q){return function(t){return function(e){return function(l){return function(k){return a(b,c,d,h,q,t,e,l,k)}}}}}}}}}b.arity=9;b.func=a;return b}function f(a,b,c){return 2===a.arity?a.func(b,c):a(b)(c)}function r(a,b,c,d){return 3===a.arity?a.func(b,c,d):a(b)(c)(d)}function T(a,b,c,d,h){return 4===a.arity?a.func(b,c,d,h):a(b)(c)(d)(h)}function v(a,b,
c,d,h,q){return 5===a.arity?a.func(b,c,d,h,q):a(b)(c)(d)(h)(q)}function tb(a,b,c,d,h,q,e){return 6===a.arity?a.func(b,c,d,h,q,e):a(b)(c)(d)(h)(q)(e)}var O=function(){function a(b,c,d){d=ea(d);if(0===d.height)d.table[b]=c;else{var l=v(b,d);0<l&&(b-=d.lengths[l-1]);d.table[l]=a(b,c,d.table[l])}return d}function b(a,d,c,l){if(0===d){var t=Array((l-c)%33);for(var k=0;k<t.length;k++)t[k]=a(c+k);return{ctor:"_Array",height:0,table:t}}var I=Math.pow(32,d);t=Array(Math.ceil((l-c)/I));var h=Array(t.length);
for(k=0;k<t.length;k++)t[k]=b(a,d-1,c+k*I,Math.min(c+(k+1)*I,l)),h[k]=E(t[k])+(0<k?h[k-1]:0);return{ctor:"_Array",height:d,table:t,lengths:h}}function c(a,b){var d=a.height;b.length===d&&b.push({ctor:"_Array",height:d+1,table:[],lengths:[]});b[d].table.push(a);a=E(a);0<b[d].lengths.length&&(a+=b[d].lengths[b[d].lengths.length-1]);b[d].lengths.push(a);32===b[d].table.length&&(c(b[d],b),b[d]={ctor:"_Array",height:d+1,table:[],lengths:[]})}function d(a,b){if(0===b.height)return 32>b.table.length?(b=
{ctor:"_Array",height:0,table:b.table.slice()},b.table.push(a),b):null;var c=d(a,b.table[b.table.length-1]);return null!==c?(b=ea(b),b.table[b.table.length-1]=c,b.lengths[b.lengths.length-1]++,b):32>b.table.length?(a=z(a,b.height-1),b=ea(b),b.table.push(a),b.lengths.push(b.lengths[b.lengths.length-1]+E(a)),b):null}function h(a,b){for(var d=b.table.length-1;0<=d;d--)a=0===b.height?A.Cons(b.table[d],a):h(a,b.table[d]);return a}function q(a,b){var d={ctor:"_Array",height:b.height,table:Array(b.table.length)};
0<b.height&&(d.lengths=b.lengths);for(var c=0;c<b.table.length;c++)d.table[c]=0===b.height?a(b.table[c]):q(a,b.table[c]);return d}function aa(a,b,d){var c={ctor:"_Array",height:b.height,table:Array(b.table.length)};0<b.height&&(c.lengths=b.lengths);for(var l=0;l<b.table.length;l++)c.table[l]=0===b.height?f(a,d+l,b.table[l]):aa(a,b.table[l],0==l?d:d+b.lengths[l-1]);return c}function t(a,b,d){if(0===d.height)for(var c=0;c<d.table.length;c++)b=f(a,d.table[c],b);else for(c=0;c<d.table.length;c++)b=t(a,
b,d.table[c]);return b}function Ja(a,b,d){if(0===d.height)for(var c=d.table.length;c--;)b=f(a,d.table[c],b);else for(c=d.table.length;c--;)b=Ja(a,b,d.table[c]);return b}function l(a,b){if(a===E(b))return b;if(0===b.height){var d={ctor:"_Array",height:0};d.table=b.table.slice(0,a);return d}var c=v(a,b);a=l(a-(0<c?b.lengths[c-1]:0),b.table[c]);if(0===c)return a;d={ctor:"_Array",height:b.height,table:b.table.slice(0,c),lengths:b.lengths.slice(0,c)};0<a.table.length&&(d.table[c]=a,d.lengths[c]=E(a)+(0<
c?d.lengths[c-1]:0));return d}function k(a,b){if(0===a)return b;if(0===b.height){var d={ctor:"_Array",height:0};d.table=b.table.slice(a,b.table.length+1);return d}d=v(a,b);a=k(a-(0<d?b.lengths[d-1]:0),b.table[d]);if(d===b.table.length-1)return a;d={ctor:"_Array",height:b.height,table:b.table.slice(d,b.table.length+1),lengths:Array(b.table.length-d)};d.table[0]=a;for(a=b=0;a<d.table.length;a++)b+=E(d.table[a]),d.lengths[a]=b;return d}function ha(a,b){if(0===a.height&&0===b.height)return[a,b];if(1!==
a.height||1!==b.height)if(a.height===b.height){a=ea(a);b=ea(b);var d=ha(a.table[a.table.length-1],b.table[0]);g(a,d[1]);Ka(b,d[0])}else if(a.height>b.height)a=ea(a),d=ha(a.table[a.table.length-1],b),g(a,d[0]),b=y(d[1],d[1].height+1);else{b=ea(b);d=ha(a,b.table[0]);a=0===d[0].table.length?0:1;var c=0===a?1:0;Ka(b,d[a]);a=y(d[c],d[c].height+1)}if(0===a.table.length||0===b.table.length)return[a,b];d=n(a,b);return 2>=d?[a,b]:La(a,b,d)}function g(a,b){var d=a.table.length-1;a.table[d]=b;a.lengths[d]=E(b);
a.lengths[d]+=0<d?a.lengths[d-1]:0}function Ka(a,b){if(0<b.table.length){a.table[0]=b;a.lengths[0]=E(b);b=E(a.table[0]);for(var d=1;d<a.lengths.length;d++)b+=E(a.table[d]),a.lengths[d]=b}else{a.table.shift();for(d=1;d<a.lengths.length;d++)a.lengths[d]-=a.lengths[0];a.lengths.shift()}}function n(a,b){for(var d=0,c=0;c<a.table.length;c++)d+=a.table[c].table.length;for(c=0;c<b.table.length;c++)d+=b.table[c].table.length;return a.table.length+b.table.length-(Math.floor((d-1)/32)+1)}function u(a,b,d){return d<
a.length?a[d]:b[d-a.length]}function ma(a,b,d,c){d<a.length?a[d]=c:b[d-a.length]=c}function za(a,b,d,c){ma(a.table,b.table,d,c);var l=0===d||d===a.lengths.length?0:u(a.lengths,a.lengths,d-1);ma(a.lengths,b.lengths,d,l+E(c))}function r(a,b){0>b&&(b=0);var d={ctor:"_Array",height:a,table:Array(b)};0<a&&(d.lengths=Array(b));return d}function La(a,b,d){for(var c=r(a.height,Math.min(32,a.table.length+b.table.length-d)),l=r(a.height,c.table.length-(a.table.length+b.table.length-d)),t=0;0===u(a.table,b.table,
t).table.length%32;)ma(c.table,l.table,t,u(a.table,b.table,t)),ma(c.lengths,l.lengths,t,u(a.lengths,b.lengths,t)),t++;for(var k=t,h=new r(a.height-1,0),m=0;t-k-(0<h.table.length?1:0)<d;){var w=u(a.table,b.table,t),q=Math.min(32-h.table.length,w.table.length);h.table=h.table.concat(w.table.slice(m,q));if(0<h.height)for(var e=h.lengths.length,ba=e;ba<e+q-m;ba++)h.lengths[ba]=E(h.table[ba]),h.lengths[ba]+=0<ba?h.lengths[ba-1]:0;m+=q;w.table.length<=q&&(t++,m=0);32===h.table.length&&(za(c,l,k,h),h=r(a.height-
1,0),k++)}0<h.table.length&&(za(c,l,k,h),k++);for(;t<a.table.length+b.table.length;)za(c,l,k,u(a.table,b.table,t)),t++,k++;return[c,l]}function ea(a){var b={ctor:"_Array",height:a.height,table:a.table.slice()};0<a.height&&(b.lengths=a.lengths.slice());return b}function E(a){return 0===a.height?a.table.length:a.lengths[a.lengths.length-1]}function v(a,b){for(var d=a>>5*b.height;b.lengths[d]<=a;)d++;return d}function z(a,b){return 0===b?{ctor:"_Array",height:0,table:[a]}:{ctor:"_Array",height:b,table:[z(a,
b-1)],lengths:[1]}}function y(a,b){return b===a.height?a:{ctor:"_Array",height:b,table:[y(a,b-1)],lengths:[E(a)]}}function B(a,b){return{ctor:"_Array",height:a.height+1,table:[a,b],lengths:[E(a),E(a)+E(b)]}}function Ma(a,b,d){for(var c=0;c<d.table.length;c++)0===d.height?a[b+c]=d.table[c]:Ma(a,b+(0===c?0:d.lengths[c-1]),d.table[c])}function Na(a,b,d,c){if(0===b)return{ctor:"_Array",height:0,table:a.slice(d,c)};for(var l=Math.pow(32,b),t=Array(Math.ceil((c-d)/l)),k=Array(t.length),h=0;h<t.length;h++)t[h]=
Na(a,b-1,d+h*l,Math.min(d+(h+1)*l,c)),k[h]=E(t[h])+(0<h?k[h-1]:0);return{ctor:"_Array",height:b,table:t,lengths:k}}var x={ctor:"_Array",height:0,table:[]};return{empty:x,fromList:function(a){if("[]"===a.ctor)return x;var b=Array(32);for(var d=[],l=0;"[]"!==a.ctor;)b[l]=a._0,a=a._1,l++,32===l&&(b={ctor:"_Array",height:0,table:b},c(b,d),b=Array(32),l=0);0<l&&(b={ctor:"_Array",height:0,table:b.splice(0,l)},c(b,d));for(a=0;a<d.length-1;a++)0<d[a].table.length&&c(d[a],d);d=d[d.length-1];return 0<d.height&&
1===d.table.length?d.table[0]:d},toList:function(a){return h(A.Nil,a)},initialize:e(function(a,d){return 0>=a?x:b(d,Math.floor(Math.log(a)/Math.log(32)),0,a)}),append:e(function(a,b){if(0===a.table.length)return b;if(0===b.table.length)return a;var d=ha(a,b);if(32>=d[0].table.length+d[1].table.length){if(0===d[0].table.length)return d[1];if(0===d[1].table.length)return d[0];d[0].table=d[0].table.concat(d[1].table);if(0<d[0].height){a=E(d[0]);for(b=0;b<d[1].lengths.length;b++)d[1].lengths[b]+=a;d[0].lengths=
d[0].lengths.concat(d[1].lengths)}return d[0]}0<d[0].height&&(a=n(a,b),2<a&&(d=La(d[0],d[1],a)));return B(d[0],d[1])}),push:e(function(a,b){var c=d(a,b);if(null!==c)return c;a=z(a,b.height);return B(b,a)}),slice:p(function(a,b,d){0>a&&(a+=E(d));0>b&&(b+=E(d));return k(a,l(b,d))}),get:e(function(a,b){if(0>a||a>=E(b))throw Error("Index "+a+" is out of range. Check the length of your array first or use getMaybe or getWithDefault.");for(var d=b.height;0<d;d--){for(var c=a>>5*d;b.lengths[c]<=a;)c++;0<
c&&(a-=b.lengths[c-1]);b=b.table[c]}return b.table[a]}),set:p(function(b,d,c){return 0>b||E(c)<=b?c:a(b,d,c)}),map:e(q),indexedMap:e(function(a,b){return aa(a,b,0)}),foldl:p(t),foldr:p(Ja),length:E,toJSArray:function(a){var b=Array(E(a));Ma(b,0,a);return b},fromJSArray:function(a){return 0===a.length?x:Na(a,Math.floor(Math.log(a.length)/Math.log(32)),0,a.length)}}}(),F=function(){function a(b,d){if(0===d)throw Error("Cannot perform mod 0. Division by zero error.");var c=b%d;b=0===b?0:0<d?0<=b?c:c+
d:-a(-b,-d);return b===d?0:b}var b=["LT","EQ","GT"];return{div:e(function(a,b){return a/b|0}),rem:e(function(a,b){return a%b}),mod:e(a),pi:Math.PI,e:Math.E,cos:Math.cos,sin:Math.sin,tan:Math.tan,acos:Math.acos,asin:Math.asin,atan:Math.atan,atan2:e(Math.atan2),degrees:function(a){return a*Math.PI/180},turns:function(a){return 2*Math.PI*a},fromPolar:function(a){var b=a._0;a=a._1;return u.Tuple2(b*Math.cos(a),b*Math.sin(a))},toPolar:function(a){var b=a._0;a=a._1;return u.Tuple2(Math.sqrt(b*b+a*a),Math.atan2(a,
b))},sqrt:Math.sqrt,logBase:e(function(a,b){return Math.log(b)/Math.log(a)}),negate:function(a){return-a},abs:function(a){return 0>a?-a:a},min:e(function(a,b){return 0>u.cmp(a,b)?a:b}),max:e(function(a,b){return 0<u.cmp(a,b)?a:b}),clamp:p(function(a,b,h){return 0>u.cmp(h,a)?a:0<u.cmp(h,b)?b:h}),compare:e(function(a,d){return{ctor:b[u.cmp(a,d)+1]}}),xor:e(function(a,b){return a!==b}),not:function(a){return!a},truncate:function(a){return a|0},ceiling:Math.ceil,floor:Math.floor,round:Math.round,toFloat:function(a){return a},
isNaN:isNaN,isInfinite:function(a){return Infinity===a||-Infinity===a}}}(),u=function(){function a(b,d,c,k){if(100<c)return k.push({x:b,y:d}),!0;if(b===d)return!0;if("object"!==typeof b){if("function"===typeof b)throw Error('Trying to use `(==)` on functions. There is no way to know if functions are "the same" in the Elm sense. Read more about this at http://package.elm-lang.org/packages/elm-lang/core/latest/Basics#== which describes why it is this way and what the better version will look like.');
return!1}if(null===b||null===d)return!1;if(b instanceof Date)return b.getTime()===d.getTime();if(!("ctor"in b)){for(var l in b)if(!a(b[l],d[l],c+1,k))return!1;return!0}if("RBNode_elm_builtin"===b.ctor||"RBEmpty_elm_builtin"===b.ctor)b=na(b),d=na(d);"Set_elm_builtin"===b.ctor&&(b=_elm_lang$core$Set$toList(b),d=_elm_lang$core$Set$toList(d));if("::"===b.ctor){for(;"::"===b.ctor&&"::"===d.ctor;){if(!a(b._0,d._0,c+1,k))return!1;b=b._1;d=d._1}return b.ctor===d.ctor}if("_Array"===b.ctor){b=O.toJSArray(b);
d=O.toJSArray(d);if(b.length!==d.length)return!1;for(l=0;l<b.length;l++)if(!a(b[l],d[l],c+1,k))return!1;return!0}if(!a(b.ctor,d.ctor,c+1,k))return!1;for(l in b)if(!a(b[l],d[l],c+1,k))return!1;return!0}function b(a,d){if("object"!==typeof a)return a===d?0:a<d?-1:1;if(a instanceof String)return a=a.valueOf(),d=d.valueOf(),a===d?0:a<d?-1:1;if("::"===a.ctor||"[]"===a.ctor){for(;"::"===a.ctor&&"::"===d.ctor;){var c=b(a._0,d._0);if(0!==c)return c;a=a._1;d=d._1}return a.ctor===d.ctor?0:"[]"===a.ctor?-1:
1}if("_Tuple"===a.ctor.slice(0,6)){var k=a.ctor.slice(6)-0;if(0===k)return 0;if(1<=k){c=b(a._0,d._0);if(0!==c)return c;if(2<=k){c=b(a._1,d._1);if(0!==c)return c;if(3<=k){c=b(a._2,d._2);if(0!==c)return c;if(4<=k){c=b(a._3,d._3);if(0!==c)return c;if(5<=k){c=b(a._4,d._4);if(0!==c)return c;if(6<=k){c=b(a._5,d._5);if(0!==c)return c;if(7<=k)throw Error("Comparison error: cannot compare tuples with more than 6 elements.");}}}}}}return 0}throw Error("Comparison error: comparison is only defined on ints, floats, times, chars, strings, lists of comparable values, and tuples of comparable values.");
}function c(a){return a.start.line==a.end.line?"on line "+a.start.line:"between lines "+a.start.line+" and "+a.end.line}function d(a){var b=typeof a;if("function"===b)return"<function>";if("boolean"===b)return a?"True":"False";if("number"===b)return a+"";if(a instanceof String)return"'"+h(a,!0)+"'";if("string"===b)return'"'+h(a,!1)+'"';if(null===a)return"null";if("object"===b&&"ctor"in a){b=a.ctor.substring(0,5);if("_Tupl"===b){b=[];for(var c in a)"ctor"!==c&&b.push(d(a[c]));return"("+b.join(",")+
")"}if("_Task"===b)return"<task>";if("_Array"===a.ctor)return a=vb(a),"Array.fromList "+d(a);if("<decoder>"===a.ctor)return"<decoder>";if("_Process"===a.ctor)return"<process:"+a.id+">";if("::"===a.ctor){b="["+d(a._0);for(a=a._1;"::"===a.ctor;)b+=","+d(a._0),a=a._1;return b+"]"}if("[]"===a.ctor)return"[]";if("Set_elm_builtin"===a.ctor)return"Set.fromList "+d(_elm_lang$core$Set$toList(a));if("RBNode_elm_builtin"===a.ctor||"RBEmpty_elm_builtin"===a.ctor)return"Dict.fromList "+d(na(a));b="";for(var k in a)if("ctor"!==
k){c=d(a[k]);var q=c[0];q="{"===q||"("===q||"<"===q||'"'===q||0>c.indexOf(" ");b+=" "+(q?c:"("+c+")")}return a.ctor+b}if("object"===b){if(a instanceof Date)return"<"+a.toString()+">";if(a.elm_web_socket)return"<websocket>";b=[];for(c in a)b.push(c+" = "+d(a[c]));return 0===b.length?"{}":"{ "+b.join(", ")+" }"}return"<internal structure>"}function h(a,b){a=a.replace(/\\/g,"\\\\").replace(/\n/g,"\\n").replace(/\t/g,"\\t").replace(/\r/g,"\\r").replace(/\v/g,"\\v").replace(/\0/g,"\\0");return b?a.replace(/\'/g,
"\\'"):a.replace(/\"/g,'\\"')}var q=0,aa={ctor:"[]"};return{eq:function(b,d){var c=[];b=a(b,d,0,c);for(var k;b&&(k=c.pop());)b=a(k.x,k.y,0,c);return b},cmp:b,Tuple0:{ctor:"_Tuple0"},Tuple2:function(a,b){return{ctor:"_Tuple2",_0:a,_1:b}},chr:function(a){return new String(a)},update:function(a,b){var d={},c;for(c in a)d[c]=a[c];for(c in b)d[c]=b[c];return d},guid:function(a){return q++},append:e(function(a,b){if("string"===typeof a)return a+b;if("[]"===a.ctor)return b;var d={ctor:"::",_0:a._0,_1:aa},
c=d;for(a=a._1;"[]"!==a.ctor;)c._1={ctor:"::",_0:a._0,_1:aa},a=a._1,c=c._1;c._1=b;return d}),crash:function(a,b){return function(d){throw Error("Ran into a `Debug.crash` in module `"+a+"` "+c(b)+"\nThe message provided by the code author is:\n\n    "+d);}},crashCase:function(a,b,l){return function(k){throw Error("Ran into a `Debug.crash` in module `"+a+"`\n\nThis was caused by the `case` expression "+c(b)+".\nOne of the branches ended with a crash and the following value got through:\n\n    "+d(l)+
"\n\nThe message provided by the code author is:\n\n    "+k);}},toString:d}}();e(function(a,b){return f(a,b._0,b._1)});p(function(a,b,c){return a({ctor:"_Tuple2",_0:b,_1:c})});p(function(a,b,c){return f(a,c,b)});var oa=e(function(a,b){return a}),n=n||{};n["<|"]=e(function(a,b){return a(b)});n=n||{};n["|>"]=e(function(a,b){return b(a)});n=n||{};n[">>"]=p(function(a,b,c){return b(a(c))});n=n||{};n["<<"]=p(function(a,b,c){return a(b(c))});n=n||{};n["++"]=u.append;var U=u.toString,wb=F.floor;n=n||{};
n["||"]=F.or;n=n||{};n["&&"]=F.and;var Oa=F.compare;n=n||{};n[">="]=F.ge;n=n||{};n["<="]=F.le;n=n||{};n[">"]=F.gt;n=n||{};n["<"]=F.lt;n=n||{};n["/="]=F.neq;n=n||{};n["=="]=F.eq;var xb=F.clamp,yb=F.negate;n=n||{};n["^"]=F.exp;n=n||{};n["%"]=F.mod;n=n||{};n["//"]=F.div;n=n||{};n["/"]=F.floatDiv;n=n||{};n["*"]=F.mul;n=n||{};n["-"]=F.sub;n=n||{};n["+"]=F.add;e(function(a,b){return"Just"===b.ctor?b._0:a});var K={ctor:"Nothing"};e(function(a,b){return"Just"===b.ctor?a(b._0):K});var L=function(a){return{ctor:"Just",
_0:a}};e(function(a,b){return"Just"===b.ctor?L(a(b._0)):K});p(function(a,b,c){return"Just"===b.ctor&&"Just"===c.ctor?L(f(a,b._0,c._0)):K});y(function(a,b,c,d){return"Just"===b.ctor&&"Just"===c.ctor&&"Just"===d.ctor?L(r(a,b._0,c._0,d._0)):K});D(function(a,b,c,d,h){return"Just"===b.ctor&&"Just"===c.ctor&&"Just"===d.ctor&&"Just"===h.ctor?L(T(a,b._0,c._0,d._0,h._0)):K});H(function(a,b,c,d,h,q){return"Just"===b.ctor&&"Just"===c.ctor&&"Just"===d.ctor&&"Just"===h.ctor&&"Just"===q.ctor?L(v(a,b._0,c._0,d._0,
h._0,q._0)):K});var A=function(){function a(a,b){return{ctor:"::",_0:a,_1:b}}function b(b){for(var c=d,h=b.length;h--;)c=a(b[h],c);return c}function c(a){for(var b=[];"[]"!==a.ctor;)b.push(a._0),a=a._1;return b}var d={ctor:"[]"};return{Nil:d,Cons:a,cons:e(a),toArray:c,fromArray:b,foldr:p(function(a,b,d){d=c(d);for(var h=d.length;h--;)b=f(a,d[h],b);return b}),map2:p(function(a,d,c){for(var h=[];"[]"!==d.ctor&&"[]"!==c.ctor;)h.push(f(a,d._0,c._0)),d=d._1,c=c._1;return b(h)}),map3:y(function(a,d,c,e){for(var h=
[];"[]"!==d.ctor&&"[]"!==c.ctor&&"[]"!==e.ctor;)h.push(r(a,d._0,c._0,e._0)),d=d._1,c=c._1,e=e._1;return b(h)}),map4:D(function(a,d,c,e,f){for(var l=[];"[]"!==d.ctor&&"[]"!==c.ctor&&"[]"!==e.ctor&&"[]"!==f.ctor;)l.push(T(a,d._0,c._0,e._0,f._0)),d=d._1,c=c._1,e=e._1,f=f._1;return b(l)}),map5:H(function(a,d,c,e,f,l){for(var k=[];"[]"!==d.ctor&&"[]"!==c.ctor&&"[]"!==e.ctor&&"[]"!==f.ctor&&"[]"!==l.ctor;)k.push(v(a,d._0,c._0,e._0,f._0,l._0)),d=d._1,c=c._1,e=e._1,f=f._1,l=l._1;return b(k)}),sortBy:e(function(a,
d){return b(c(d).sort(function(b,d){return u.cmp(a(b),a(d))}))}),sortWith:e(function(a,d){return b(c(d).sort(function(b,d){b=a(b)(d).ctor;return"EQ"===b?0:"LT"===b?-1:1}))})}}();e(function(a,b){for(;;){if(1>u.cmp(a,0))return b;var c=b;if("[]"===c.ctor)return b;b=c._1;--a}});var zb=A.map2,Pa=e(function(a,b){for(;;){if("[]"===b.ctor)return!1;if(a(b._0))return!0;b=b._1}});e(function(a,b){return!f(Pa,function(b){return!a(b)},b)});var V=A.foldr,ca=p(function(a,b,c){for(;;){var d=c;if("[]"===d.ctor)return b;
c=a;b=f(a,d._0,b);d=d._1;a=c;c=d}}),Ab=function(a){return r(ca,e(function(a,c){return c+1}),0,a)};e(function(a,b){return f(Pa,function(b){return u.eq(b,a)},b)});var Qa=Qa||{};Qa["::"]=A.cons;var pa=e(function(a,b){return r(V,e(function(b,d){return{ctor:"::",_0:a(b),_1:d}}),{ctor:"[]"},b)});e(function(a,b){var c=e(function(b,c){return a(b)?{ctor:"::",_0:b,_1:c}:c});return r(V,c,{ctor:"[]"},b)});var Bb=p(function(a,b,c){a=a(b);return"Just"===a.ctor?{ctor:"::",_0:a._0,_1:c}:c});e(function(a,b){return r(V,
Bb(a),{ctor:"[]"},b)});var Ra=function(a){return r(ca,e(function(a,c){return{ctor:"::",_0:a,_1:c}}),{ctor:"[]"},a)};p(function(a,b,c){var d=e(function(b,d){return"::"===d.ctor?{ctor:"::",_0:f(a,b,d._0),_1:d}:{ctor:"[]"}});return Ra(r(ca,d,{ctor:"::",_0:b,_1:{ctor:"[]"}},c))});var Cb=e(function(a,b){return"[]"===b.ctor?a:r(V,e(function(a,b){return{ctor:"::",_0:a,_1:b}}),b,a)});e(function(a,b){return r(V,Cb,{ctor:"[]"},f(pa,a,b))});e(function(a,b){var c=e(function(b,c){var d=c._0;c=c._1;return a(b)?
{ctor:"_Tuple2",_0:{ctor:"::",_0:b,_1:d},_1:c}:{ctor:"_Tuple2",_0:d,_1:{ctor:"::",_0:b,_1:c}}});return r(V,c,{ctor:"_Tuple2",_0:{ctor:"[]"},_1:{ctor:"[]"}},b)});e(function(a,b){if("[]"===b.ctor)return{ctor:"[]"};var c=e(function(b,c){return{ctor:"::",_0:a,_1:{ctor:"::",_0:b,_1:c}}});c=r(V,c,{ctor:"[]"},b._1);return{ctor:"::",_0:b._0,_1:c}});var Db=p(function(a,b,c){for(;;){if(1>u.cmp(a,0))return c;var d=b;if("[]"===d.ctor)return c;b=d._1;c={ctor:"::",_0:d._0,_1:c};--a}}),Eb=e(function(a,b){return Ra(r(Db,
a,b,{ctor:"[]"}))}),Sa=p(function(a,b,c){if(1>u.cmp(b,0))return{ctor:"[]"};a:do{b:do{if("[]"===c.ctor)return c;if("::"===c._1.ctor)switch(b){case 1:break b;case 2:return{ctor:"::",_0:c._0,_1:{ctor:"::",_0:c._1._0,_1:{ctor:"[]"}}};case 3:if("::"===c._1._1.ctor)return{ctor:"::",_0:c._0,_1:{ctor:"::",_0:c._1._0,_1:{ctor:"::",_0:c._1._1._0,_1:{ctor:"[]"}}}};break a;default:if("::"===c._1._1.ctor&&"::"===c._1._1._1.ctor){var d=c._1._1._0,h=c._1._0,e=c._0,aa=c._1._1._1._0;c=c._1._1._1._1;return 0<u.cmp(a,
1E3)?{ctor:"::",_0:e,_1:{ctor:"::",_0:h,_1:{ctor:"::",_0:d,_1:{ctor:"::",_0:aa,_1:f(Eb,b-4,c)}}}}:{ctor:"::",_0:e,_1:{ctor:"::",_0:h,_1:{ctor:"::",_0:d,_1:{ctor:"::",_0:aa,_1:r(Sa,a+1,b-4,c)}}}}}break a}else if(1===b)break b;else break a}while(0);return{ctor:"::",_0:c._0,_1:{ctor:"[]"}}}while(0);return c});e(function(a,b){return r(Sa,0,a,b)});var Fb=p(function(a,b,c){for(;;){if(1>u.cmp(b,0))return a;--b;var d=c;a={ctor:"::",_0:c,_1:a};c=d}});e(function(a,b){return r(Fb,{ctor:"[]"},a,b)});var Gb=p(function(a,
b,c){for(;;)if(1>u.cmp(a,b))c={ctor:"::",_0:b,_1:c},--b;else return c}),Hb=e(function(a,b){return r(Gb,a,b,{ctor:"[]"})});e(function(a,b){return r(zb,a,f(Hb,0,Ab(b)-1),b)});e(function(a,b){return 1>u.cmp(0,a)&&0>u.cmp(a,O.length(b))?L(f(O.get,a,b)):K});e(function(a,b){var c=e(function(b,c){return a(b)?f(O.push,b,c):c});return r(O.foldl,c,O.empty,b)});var vb=O.toList,Ib=O.initialize;e(function(a,b){return f(Ib,a,oa(b))});var fa=function(){return{crash:function(a){throw Error(a);},log:e(function(a,
b){a=a+": "+u.toString(b);var c=c||{};c.stdout?c.stdout.write(a):console.log(a);return b})}}(),Jb=function(){function a(a,b){for(var d="";0<a;)a&1&&(d+=b),a>>=1,b+=b;return d}function b(a){return x("could not convert string '"+a+"' to an Int")}function c(a){return x("could not convert string '"+a+"' to a Float")}return{isEmpty:function(a){return 0===a.length},cons:e(function(a,b){return a+b}),uncons:function(a){var b=a[0];return b?L(u.Tuple2(u.chr(b),a.slice(1))):K},append:e(function(a,b){return a+
b}),concat:function(a){return A.toArray(a).join("")},length:function(a){return a.length},map:e(function(a,b){b=b.split("");for(var d=b.length;d--;)b[d]=a(u.chr(b[d]));return b.join("")}),filter:e(function(a,b){return b.split("").map(u.chr).filter(a).join("")}),reverse:function(a){return a.split("").reverse().join("")},foldl:p(function(a,b,c){for(var d=c.length,e=0;e<d;++e)b=f(a,u.chr(c[e]),b);return b}),foldr:p(function(a,b,c){for(var d=c.length;d--;)b=f(a,u.chr(c[d]),b);return b}),split:e(function(a,
b){return A.fromArray(b.split(a))}),join:e(function(a,b){return A.toArray(b).join(a)}),repeat:e(a),slice:p(function(a,b,c){return c.slice(a,b)}),left:e(function(a,b){return 1>a?"":b.slice(0,a)}),right:e(function(a,b){return 1>a?"":b.slice(-a)}),dropLeft:e(function(a,b){return 1>a?b:b.slice(a)}),dropRight:e(function(a,b){return 1>a?b:b.slice(0,-a)}),pad:p(function(b,c,e){b=(b-e.length)/2;return a(Math.ceil(b),c)+e+a(b|0,c)}),padLeft:p(function(b,c,e){return a(b-e.length,c)+e}),padRight:p(function(b,
c,e){return e+a(b-e.length,c)}),trim:function(a){return a.trim()},trimLeft:function(a){return a.replace(/^\s+/,"")},trimRight:function(a){return a.replace(/\s+$/,"")},words:function(a){return A.fromArray(a.trim().split(/\s+/g))},lines:function(a){return A.fromArray(a.split(/\r\n|\r|\n/g))},toUpper:function(a){return a.toUpperCase()},toLower:function(a){return a.toLowerCase()},any:e(function(a,b){for(var d=b.length;d--;)if(a(u.chr(b[d])))return!0;return!1}),all:e(function(a,b){for(var d=b.length;d--;)if(!a(u.chr(b[d])))return!1;
return!0}),contains:e(function(a,b){return-1<b.indexOf(a)}),startsWith:e(function(a,b){return 0===b.indexOf(a)}),endsWith:e(function(a,b){return b.length>=a.length&&b.lastIndexOf(a)===b.length-a.length}),indexes:e(function(a,b){var d=a.length;if(1>d)return A.Nil;for(var c=0,e=[];-1<(c=b.indexOf(a,c));)e.push(c),c+=d;return A.fromArray(e)}),toInt:function(a){var d=a.length;if(0===d)return b(a);var c=a[0];if("0"===c&&"x"===a[1]){for(var e=2;e<d;++e)if(c=a[e],!("0"<=c&&"9">=c||"A"<=c&&"F">=c||"a"<=c&&
"f">=c))return b(a);return M(parseInt(a,16))}if("9"<c||"0">c&&"-"!==c&&"+"!==c)return b(a);for(e=1;e<d;++e)if(c=a[e],"0">c||"9"<c)return b(a);return M(parseInt(a,10))},toFloat:function(a){if(0===a.length||/[\sxbo]/.test(a))return c(a);var b=+a;return b===b?M(b):c(a)},toList:function(a){return A.fromArray(a.split("").map(u.chr))},fromList:function(a){return A.toArray(a).join("")}}}(),Aa=function(){return{fromCode:function(a){return u.chr(String.fromCharCode(a))},toCode:function(a){return a.charCodeAt(0)},
toUpper:function(a){return u.chr(a.toUpperCase())},toLower:function(a){return u.chr(a.toLowerCase())},toLocaleUpper:function(a){return u.chr(a.toLocaleUpperCase())},toLocaleLower:function(a){return u.chr(a.toLocaleLowerCase())}}}().toCode,qa=p(function(a,b,c){c=Aa(c);return-1<u.cmp(c,Aa(a))&&1>u.cmp(c,Aa(b))});f(qa,u.chr("A"),u.chr("Z"));f(qa,u.chr("a"),u.chr("z"));f(qa,u.chr("0"),u.chr("9"));f(qa,u.chr("0"),u.chr("7"));e(function(a,b){return"Ok"===b.ctor?b._0:a});var x=function(a){return{ctor:"Err",
_0:a}};e(function(a,b){return"Ok"===b.ctor?a(b._0):x(b._0)});var M=function(a){return{ctor:"Ok",_0:a}};e(function(a,b){return"Ok"===b.ctor?M(a(b._0)):x(b._0)});p(function(a,b,c){return"Ok"===b.ctor?"Ok"===c.ctor?M(f(a,b._0,c._0)):x(c._0):x(b._0)});y(function(a,b,c,d){return"Ok"===b.ctor?"Ok"===c.ctor?"Ok"===d.ctor?M(r(a,b._0,c._0,d._0)):x(d._0):x(c._0):x(b._0)});D(function(a,b,c,d,e){return"Ok"===b.ctor?"Ok"===c.ctor?"Ok"===d.ctor?"Ok"===e.ctor?M(T(a,b._0,c._0,d._0,e._0)):x(e._0):x(d._0):x(c._0):
x(b._0)});H(function(a,b,c,d,e,f){return"Ok"===b.ctor?"Ok"===c.ctor?"Ok"===d.ctor?"Ok"===e.ctor?"Ok"===f.ctor?M(v(a,b._0,c._0,d._0,e._0,f._0)):x(f._0):x(e._0):x(d._0):x(c._0):x(b._0)});e(function(a,b){return"Ok"===b.ctor?M(b._0):x(a(b._0))});e(function(a,b){return"Just"===b.ctor?M(b._0):x(a)});var Kb=Jb.concat,Ta=p(function(a,b,c){for(;;){var d=c;if("RBEmpty_elm_builtin"===d.ctor)return b;c=a;b=r(a,d._1,d._2,r(Ta,a,b,d._4));d=d._3;a=c;c=d}}),na=function(a){return r(Ta,p(function(a,c,d){return{ctor:"::",
_0:{ctor:"_Tuple2",_0:a,_1:c},_1:d}}),{ctor:"[]"},a)},X=p(function(a,b,c){for(;;){var d=c;if("RBEmpty_elm_builtin"===d.ctor)return b;c=a;b=r(a,d._1,d._2,r(X,a,b,d._3));d=d._4;a=c;c=d}}),Lb=H(function(a,b,c,d,h,f){var q=p(function(d,e,l){for(;;){var k=l;l=k._1;var h=k._0,f=h;if("[]"===f.ctor)return{ctor:"_Tuple2",_0:h,_1:r(c,d,e,l)};k=f._1;var q=f._0._1;f=f._0._0;if(0>u.cmp(f,d))l={ctor:"_Tuple2",_0:k,_1:r(a,f,q,l)};else return 0<u.cmp(f,d)?{ctor:"_Tuple2",_0:h,_1:r(c,d,e,l)}:{ctor:"_Tuple2",_0:k,
_1:T(b,f,q,e,l)}}});h=r(X,q,{ctor:"_Tuple2",_0:na(d),_1:f},h);d=h._0;h=h._1;return r(ca,e(function(b,d){return r(a,b._0,b._1,d)}),h,d)}),Ua=y(function(a,b,c,d){return fa.crash(Kb({ctor:"::",_0:"Internal red-black tree invariant violated, expected ",_1:{ctor:"::",_0:a,_1:{ctor:"::",_0:" and got ",_1:{ctor:"::",_0:U(b),_1:{ctor:"::",_0:"/",_1:{ctor:"::",_0:c,_1:{ctor:"::",_0:"/",_1:{ctor:"::",_0:d,_1:{ctor:"::",_0:"\nPlease report this bug to <https://github.com/elm-lang/core/issues>",_1:{ctor:"[]"}}}}}}}}}}))}),
Va=function(a){a:do{if("RBNode_elm_builtin"===a.ctor){if("BBlack"===a._0.ctor)return!0}else if("LBBlack"===a._0.ctor)return!0;break a}while(0);return!1},Mb=e(function(a,b){for(;;){if("RBEmpty_elm_builtin"===b.ctor)return a;a=f(Mb,a+1,b._4);b=b._3}}),Ba=e(function(a,b){a:for(;;){if("RBEmpty_elm_builtin"===b.ctor)return K;switch(f(Oa,a,b._1).ctor){case "LT":b=b._3;continue a;case "EQ":return L(b._2);default:b=b._4}}}),Nb=e(function(a,b){return"Just"===f(Ba,a,b).ctor?!0:!1}),Ob=p(function(a,b,c){for(;;){if("RBEmpty_elm_builtin"===
c.ctor)return{ctor:"_Tuple2",_0:a,_1:b};b=c._2;var d=c._4;a=c._1;c=d}}),Pb={ctor:"NBlack"},Wa={ctor:"BBlack"},J={ctor:"Black"},ra={ctor:"Red"},Qb=function(a){switch(a.ctor){case "Black":return Wa;case "Red":return J;case "NBlack":return ra;default:return fa.crash("Can't make a double black node more black!")}},Xa=function(a){switch(a.ctor){case "BBlack":return J;case "Black":return ra;case "Red":return Pb;default:return fa.crash("Can't make a negative black node less black!")}},Rb={ctor:"LBBlack"},
ja={ctor:"LBlack"},Y=function(a){return{ctor:"RBEmpty_elm_builtin",_0:a}},R=Y(ja),G=D(function(a,b,c,d,e){return{ctor:"RBNode_elm_builtin",_0:a,_1:b,_2:c,_3:d,_4:e}}),Sb=function(a){return"RBNode_elm_builtin"===a.ctor&&"Red"===a._0.ctor?v(G,J,a._1,a._2,a._3,a._4):a},Ya=function(a){return"RBNode_elm_builtin"===a.ctor?v(G,Xa(a._0),a._1,a._2,a._3,a._4):Y(ja)},sa=function(a){return function(b){return function(c){return function(d){return function(e){return function(h){return function(f){return function(q){return function(t){return function(l){return function(k){return v(G,
Xa(a),d,e,v(G,J,b,c,q,t),v(G,J,h,f,l,k))}}}}}}}}}}},Tb=function(a){return"RBEmpty_elm_builtin"===a.ctor?Y(ja):v(G,J,a._1,a._2,a._3,a._4)},Za=function(a){return"RBEmpty_elm_builtin"===a.ctor?fa.crash("can't make a Leaf red"):v(G,ra,a._1,a._2,a._3,a._4)},Ub=function(a){a:do{b:do{c:do{d:do{e:do{f:do{g:do if("RBNode_elm_builtin"===a.ctor)if("RBNode_elm_builtin"===a._3.ctor)if("RBNode_elm_builtin"===a._4.ctor)switch(a._3._0.ctor){case "Red":switch(a._4._0.ctor){case "Red":if("RBNode_elm_builtin"===a._3._3.ctor&&
"Red"===a._3._3._0.ctor)break g;else if("RBNode_elm_builtin"===a._3._4.ctor&&"Red"===a._3._4._0.ctor)break f;else if("RBNode_elm_builtin"===a._4._3.ctor&&"Red"===a._4._3._0.ctor)break e;else if("RBNode_elm_builtin"===a._4._4.ctor&&"Red"===a._4._4._0.ctor)break d;else break a;case "NBlack":if("RBNode_elm_builtin"===a._3._3.ctor&&"Red"===a._3._3._0.ctor)break g;else if("RBNode_elm_builtin"===a._3._4.ctor&&"Red"===a._3._4._0.ctor)break f;else if("BBlack"===a._0.ctor&&"RBNode_elm_builtin"===a._4._3.ctor&&
"Black"===a._4._3._0.ctor&&"RBNode_elm_builtin"===a._4._4.ctor&&"Black"===a._4._4._0.ctor)break c;else break a;default:if("RBNode_elm_builtin"===a._3._3.ctor&&"Red"===a._3._3._0.ctor)break g;else if("RBNode_elm_builtin"===a._3._4.ctor&&"Red"===a._3._4._0.ctor)break f;else break a}case "NBlack":switch(a._4._0.ctor){case "Red":if("RBNode_elm_builtin"===a._4._3.ctor&&"Red"===a._4._3._0.ctor)break e;else if("RBNode_elm_builtin"===a._4._4.ctor&&"Red"===a._4._4._0.ctor)break d;else if("BBlack"===a._0.ctor&&
"RBNode_elm_builtin"===a._3._3.ctor&&"Black"===a._3._3._0.ctor&&"RBNode_elm_builtin"===a._3._4.ctor&&"Black"===a._3._4._0.ctor)break b;else break a;case "NBlack":if("BBlack"===a._0.ctor)if("RBNode_elm_builtin"===a._4._3.ctor&&"Black"===a._4._3._0.ctor&&"RBNode_elm_builtin"===a._4._4.ctor&&"Black"===a._4._4._0.ctor)break c;else if("RBNode_elm_builtin"===a._3._3.ctor&&"Black"===a._3._3._0.ctor&&"RBNode_elm_builtin"===a._3._4.ctor&&"Black"===a._3._4._0.ctor)break b;else break a;else break a;default:if("BBlack"===
a._0.ctor&&"RBNode_elm_builtin"===a._3._3.ctor&&"Black"===a._3._3._0.ctor&&"RBNode_elm_builtin"===a._3._4.ctor&&"Black"===a._3._4._0.ctor)break b;else break a}default:switch(a._4._0.ctor){case "Red":if("RBNode_elm_builtin"===a._4._3.ctor&&"Red"===a._4._3._0.ctor)break e;else if("RBNode_elm_builtin"===a._4._4.ctor&&"Red"===a._4._4._0.ctor)break d;else break a;case "NBlack":if("BBlack"===a._0.ctor&&"RBNode_elm_builtin"===a._4._3.ctor&&"Black"===a._4._3._0.ctor&&"RBNode_elm_builtin"===a._4._4.ctor&&
"Black"===a._4._4._0.ctor)break c;else break a;default:break a}}else switch(a._3._0.ctor){case "Red":if("RBNode_elm_builtin"===a._3._3.ctor&&"Red"===a._3._3._0.ctor)break g;else if("RBNode_elm_builtin"===a._3._4.ctor&&"Red"===a._3._4._0.ctor)break f;else break a;case "NBlack":if("BBlack"===a._0.ctor&&"RBNode_elm_builtin"===a._3._3.ctor&&"Black"===a._3._3._0.ctor&&"RBNode_elm_builtin"===a._3._4.ctor&&"Black"===a._3._4._0.ctor)break b;else break a;default:break a}else if("RBNode_elm_builtin"===a._4.ctor)switch(a._4._0.ctor){case "Red":if("RBNode_elm_builtin"===
a._4._3.ctor&&"Red"===a._4._3._0.ctor)break e;else if("RBNode_elm_builtin"===a._4._4.ctor&&"Red"===a._4._4._0.ctor)break d;else break a;case "NBlack":if("BBlack"===a._0.ctor&&"RBNode_elm_builtin"===a._4._3.ctor&&"Black"===a._4._3._0.ctor&&"RBNode_elm_builtin"===a._4._4.ctor&&"Black"===a._4._4._0.ctor)break c;else break a;default:break a}else break a;else break a;while(0);return sa(a._0)(a._3._3._1)(a._3._3._2)(a._3._1)(a._3._2)(a._1)(a._2)(a._3._3._3)(a._3._3._4)(a._3._4)(a._4)}while(0);return sa(a._0)(a._3._1)(a._3._2)(a._3._4._1)(a._3._4._2)(a._1)(a._2)(a._3._3)(a._3._4._3)(a._3._4._4)(a._4)}while(0);
return sa(a._0)(a._1)(a._2)(a._4._3._1)(a._4._3._2)(a._4._1)(a._4._2)(a._3)(a._4._3._3)(a._4._3._4)(a._4._4)}while(0);return sa(a._0)(a._1)(a._2)(a._4._1)(a._4._2)(a._4._4._1)(a._4._4._2)(a._3)(a._4._3)(a._4._4._3)(a._4._4._4)}while(0);return v(G,J,a._4._3._1,a._4._3._2,v(G,J,a._1,a._2,a._3,a._4._3._3),v(ka,J,a._4._1,a._4._2,a._4._3._4,Za(a._4._4)))}while(0);return v(G,J,a._3._4._1,a._3._4._2,v(ka,J,a._3._1,a._3._2,Za(a._3._3),a._3._4._3),v(G,J,a._1,a._2,a._3._4._4,a._4))}while(0);return a},ka=D(function(a,
b,c,d,e){a=v(G,a,b,c,d,e);"RBNode_elm_builtin"===a.ctor?(b=a._0,b=u.eq(b,J)||u.eq(b,Wa)):b=!0;return b?Ub(a):a}),ta=D(function(a,b,c,d,e){return Va(d)||Va(e)?v(ka,Qb(a),b,c,Ya(d),Ya(e)):v(G,a,b,c,d,e)}),ab=D(function(a,b,c,d,e){return"RBEmpty_elm_builtin"===e.ctor?r($a,a,d,e):v(ta,a,b,c,d,v(ab,e._0,e._1,e._2,e._3,e._4))}),$a=p(function(a,b,c){if("RBEmpty_elm_builtin"===b.ctor)if("RBEmpty_elm_builtin"===c.ctor)switch(a.ctor){case "Red":return Y(ja);case "Black":return Y(Rb);default:return fa.crash("cannot have bblack or nblack nodes at this point")}else{var d=
c._0;b=b._0;return"Black"===a.ctor&&"LBlack"===b.ctor&&"Red"===d.ctor?v(G,J,c._1,c._2,c._3,c._4):T(Ua,"Black/LBlack/Red",a,U(b),U(d))}else{if("RBEmpty_elm_builtin"===c.ctor)return c=c._0,d=b._0,"Black"===a.ctor&&"Red"===d.ctor&&"LBlack"===c.ctor?v(G,J,b._1,b._2,b._3,b._4):T(Ua,"Black/Red/LBlack",a,U(d),U(c));d=b._2;var e=b._4,f=b._1;b=v(ab,b._0,f,d,b._3,e);d=r(Ob,f,d,e);return v(ta,a,d._0,d._1,b,c)}}),bb=e(function(a,b){if("RBEmpty_elm_builtin"===b.ctor)return Y(ja);var c=b._1;return v(G,b._0,c,f(a,
c,b._2),f(bb,a,b._3),f(bb,a,b._4))}),ua={ctor:"Same"},Ca={ctor:"Remove"},Da={ctor:"Insert"},cb=p(function(a,b,c){var d=function(c){if("RBEmpty_elm_builtin"===c.ctor){var e=b(K);return"Nothing"===e.ctor?{ctor:"_Tuple2",_0:ua,_1:R}:{ctor:"_Tuple2",_0:Da,_1:v(G,ra,a,e._0,R,R)}}var h=c._2,q=c._4,l=c._3;e=c._1;c=c._0;switch(f(Oa,a,e).ctor){case "EQ":return h=b(L(h)),"Nothing"===h.ctor?{ctor:"_Tuple2",_0:Ca,_1:r($a,c,l,q)}:{ctor:"_Tuple2",_0:ua,_1:v(G,c,e,h._0,l,q)};case "LT":l=d(l);var k=l._0;l=l._1;switch(k.ctor){case "Same":return{ctor:"_Tuple2",
_0:ua,_1:v(G,c,e,h,l,q)};case "Insert":return{ctor:"_Tuple2",_0:Da,_1:v(ka,c,e,h,l,q)};default:return{ctor:"_Tuple2",_0:Ca,_1:v(ta,c,e,h,l,q)}}default:switch(q=d(q),k=q._0,q=q._1,k.ctor){case "Same":return{ctor:"_Tuple2",_0:ua,_1:v(G,c,e,h,l,q)};case "Insert":return{ctor:"_Tuple2",_0:Da,_1:v(ka,c,e,h,l,q)};default:return{ctor:"_Tuple2",_0:Ca,_1:v(ta,c,e,h,l,q)}}}};c=d(c);var e=c._1;switch(c._0.ctor){case "Same":return e;case "Insert":return Sb(e);default:return Tb(e)}}),S=p(function(a,b,c){return r(cb,
a,oa(L(b)),c)});e(function(a,b){return r(S,a,b,R)});e(function(a,b){return r(X,S,b,a)});var Vb=e(function(a,b){var c=p(function(b,c,e){return f(a,b,c)?r(S,b,c,e):e});return r(X,c,R,b)});e(function(a,b){return f(Vb,e(function(a,d){return f(Nb,a,b)}),a)});e(function(a,b){var c=p(function(b,c,e){var d=e._1;e=e._0;return f(a,b,c)?{ctor:"_Tuple2",_0:r(S,b,c,e),_1:d}:{ctor:"_Tuple2",_0:e,_1:r(S,b,c,d)}});return r(X,c,{ctor:"_Tuple2",_0:R,_1:R},b)});var Wb=e(function(a,b){return r(cb,a,oa(K),b)});e(function(a,
b){return r(X,p(function(a,b,e){return f(Wb,a,e)}),a,b)});var N=function(){function a(a,b){return{ctor:"<decoder>",tag:"map-many",func:a,decoders:b}}function b(a){return{tag:"ok",value:a}}function c(a,b){return{tag:"primitive",type:a,value:b}}function d(a,b){return{tag:"index",index:a,rest:b}}function d(a,b){return{tag:"index",index:a,rest:b}}function f(a){for(var b="_";a;)switch(a.tag){case "primitive":return b="Expecting "+a.type+("_"===b?"":" at "+b)+" but instead got: ",a=a.value,a=void 0===a?
"undefined":JSON.stringify(a),b+a;case "index":b+="["+a.index+"]";a=a.rest;break;case "field":b+="."+a.field;a=a.rest;break;case "oneOf":a=a.problems;for(var c=0;c<a.length;c++)a[c]=f(a[c]);return"I ran into the following problems"+("_"===b?"":" at "+b)+":\n\n"+a.join("\n");case "fail":return"I ran into a `fail` decoder"+("_"===b?"":" at "+b)+": "+a.msg}}function q(a,b){a=g(a,b);return"ok"===a.tag?M(a.value):x(f(a))}function g(a,e){switch(a.tag){case "bool":return"boolean"===typeof e?b(e):c("a Bool",
e);case "int":return"number"!==typeof e?c("an Int",e):-2147483647<e&&2147483647>e&&(e|0)===e||isFinite(e)&&!(e%1)?b(e):c("an Int",e);case "float":return"number"===typeof e?b(e):c("a Float",e);case "string":return"string"===typeof e?b(e):e instanceof String?b(e+""):c("a String",e);case "null":return null===e?b(a.value):c("null",e);case "value":return b(e);case "list":if(!(e instanceof Array))return c("a List",e);for(var l=A.Nil,k=e.length;k--;){var f=g(a.decoder,e[k]);if("ok"!==f.tag)return d(k,f);
l=A.Cons(f.value,l)}return b(l);case "array":if(!(e instanceof Array))return c("an Array",e);f=e.length;l=Array(f);for(k=f;k--;){f=g(a.decoder,e[k]);if("ok"!==f.tag)return d(k,f);l[k]=f.value}return b(O.fromJSArray(l));case "maybe":return f=g(a.decoder,e),"ok"===f.tag?b(L(f.value)):b(K);case "field":k=a.field;if("object"!==typeof e||null===e||!(k in e))return c("an object with a field named `"+k+"`",e);f=g(a.decoder,e[k]);return"ok"===f.tag?f:{tag:"field",field:k,rest:f};case "index":k=a.index;if(!(e instanceof
Array))return c("an array",e);if(k>=e.length)return c("a longer array. Need index "+k+" but there are only "+e.length+" entries",e);f=g(a.decoder,e[k]);return"ok"===f.tag?f:d(k,f);case "key-value":if("object"!==typeof e||null===e||e instanceof Array)return c("an object",e);k=A.Nil;for(l in e){f=g(a.decoder,e[l]);if("ok"!==f.tag)return{tag:"field",field:l,rest:f};f=u.Tuple2(l,f.value);k=A.Cons(f,k)}return b(k);case "map-many":l=a.func;a=a.decoders;for(k=0;k<a.length;k++){f=g(a[k],e);if("ok"!==f.tag)return f;
l=l(f.value)}return b(l);case "andThen":return f=g(a.decoder,e),"ok"!==f.tag?f:g(a.callback(f.value),e);case "oneOf":k=[];for(a=a.decoders;"[]"!==a.ctor;){f=g(a._0,e);if("ok"===f.tag)return f;k.push(f);a=a._1}return{tag:"oneOf",problems:k};case "fail":return{tag:"fail",msg:a.msg};case "succeed":return b(a.msg)}}function t(a,b){if(a===b)return!0;if(a.tag!==b.tag)return!1;switch(a.tag){case "succeed":case "fail":return a.msg===b.msg;case "bool":case "int":case "float":case "string":case "value":return!0;
case "null":return a.value===b.value;case "list":case "array":case "maybe":case "key-value":return t(a.decoder,b.decoder);case "field":return a.field===b.field&&t(a.decoder,b.decoder);case "index":return a.index===b.index&&t(a.decoder,b.decoder);case "map-many":return a.func!==b.func?!1:n(a.decoders,b.decoders);case "andThen":return a.callback===b.callback&&t(a.decoder,b.decoder);case "oneOf":return n(a.decoders,b.decoders)}}function n(a,b){var c=a.length;if(c!==b.length)return!1;for(var d=0;d<c;d++)if(!t(a[d],
b[d]))return!1;return!0}return{encode:e(function(a,b){return JSON.stringify(b,null,a)}),runOnString:e(function(a,b){try{var c=JSON.parse(b)}catch(ub){return x("Given an invalid JSON: "+ub.message)}return q(a,c)}),run:e(q),decodeNull:function(a){return{ctor:"<decoder>",tag:"null",value:a}},decodePrimitive:function(a){return{ctor:"<decoder>",tag:a}},decodeContainer:e(function(a,b){return{ctor:"<decoder>",tag:a,decoder:b}}),decodeField:e(function(a,b){return{ctor:"<decoder>",tag:"field",field:a,decoder:b}}),
decodeIndex:e(function(a,b){return{ctor:"<decoder>",tag:"index",index:a,decoder:b}}),map1:e(function(b,c){return a(b,[c])}),map2:p(function(b,c,d){return a(b,[c,d])}),map3:y(function(b,c,d,e){return a(b,[c,d,e])}),map4:D(function(b,c,d,e,f){return a(b,[c,d,e,f])}),map5:H(function(b,c,d,e,f,h){return a(b,[c,d,e,f,h])}),map6:la(function(b,c,d,e,f,h,g){return a(b,[c,d,e,f,h,g])}),map7:Z(function(b,c,d,e,f,h,g,q){return a(b,[c,d,e,f,h,g,q])}),map8:sb(function(b,c,d,e,f,h,g,q,t){return a(b,[c,d,e,f,h,
g,q,t])}),decodeKeyValuePairs:function(a){return{ctor:"<decoder>",tag:"key-value",decoder:a}},andThen:e(function(a,b){return{ctor:"<decoder>",tag:"andThen",decoder:b,callback:a}}),fail:function(a){return{ctor:"<decoder>",tag:"fail",msg:a}},succeed:function(a){return{ctor:"<decoder>",tag:"succeed",msg:a}},oneOf:function(a){return{ctor:"<decoder>",tag:"oneOf",decoders:a}},identity:function(a){return a},encodeNull:null,encodeArray:O.toJSArray,encodeList:A.toArray,encodeObject:function(a){for(var b={};"[]"!==
a.ctor;){var c=a._0;b[c._0]=c._1;a=a._1}return b},equality:t}}(),Xb=N.identity,Yb=N.identity;N.decodePrimitive("value");var db=N.run,Zb=N.map3,$b=N.map1,va=N.decodeField;e(function(a,b){return r(V,va,b,a)});var Ea=N.decodePrimitive("float");N.decodePrimitive("int");N.decodePrimitive("bool");N.decodePrimitive("string");e(function(a,b){return{ctor:"_Tuple2",_0:b._0,_1:a(b._1)}});e(function(a,b){return{ctor:"_Tuple2",_0:a(b._0),_1:b._1}});var P=function(){function a(a,b){return function(a){}}function b(a,
b,d,e){function k(a){z.rawSend(p,a)}var l={},g,q=z.nativeBinding(function(b){var c=a._0;g=e(k,c);var f=a._1,h=d(c);t(l,f,h);b(z.succeed(c))}),p=h(q,function(a,c){return z.nativeBinding(function(e){var k=f(b,a,c);c=k._0;g(c);k=k._1;var h=d(c);t(l,k,h);e(z.succeed(c))})});return(q=c(l,k))?{ports:q}:{}}function c(a,b){var c;for(c in x){var e=x[c];if(e.isForeign){var f=f||{};f[c]="cmd"===e.tag?ha(c):y(c,b)}a[c]=d(e,b)}return f}function d(a,b){var c={main:b,self:void 0},d=a.tag,e=a.onEffects,f=a.onSelfMsg;
a=h(a.init,function(a,b){if("self"===a.ctor)return r(f,c,a._0,b);a=a._0;switch(d){case "cmd":return r(e,c,a.cmds,b);case "sub":return r(e,c,a.subs,b);case "fx":return T(e,c,a.cmds,a.subs,b)}});return c.self=a}function h(a,b){function c(a){var e=z.receive(function(c){return b(c,a)});return f(d,c,e)}var d=z.andThen;a=f(d,c,a);return z.rawSpawn(a)}function g(a){return function(b){return{type:"leaf",home:a,value:b}}}function n(a){return{type:"node",branches:a}}function t(a,b,c){var d={};v(!0,b,d,null);
v(!1,c,d,null);for(var e in a)z.rawSend(a[e],{ctor:"fx",_0:e in d?d[e]:{cmds:A.Nil,subs:A.Nil}})}function v(a,b,c,d){switch(b.type){case "leaf":var e=b.home;d=l(a,e,d,b.value);b=(b=c[e])||{cmds:A.Nil,subs:A.Nil};a?b.cmds=A.Cons(d,b.cmds):b.subs=A.Cons(d,b.subs);c[e]=b;break;case "node":for(e=b.branches;"[]"!==e.ctor;)v(a,e._0,c,d),e=e._1;break;case "map":v(a,b.tree,c,{tagger:b.tagger,rest:d})}}function l(a,b,c,d){return f(a?x[b].cmdMap:x[b].subMap,function(a){for(var b=c;b;)a=b.tagger(a),b=b.rest;
return a},d)}function k(a){if(a in x)throw Error("There can only be one port named `"+a+"`, but your program has multiple.");}function ha(a){var b=[],c=x[a].converter,d=z.succeed(null);x[a].init=d;x[a].onEffects=p(function(a,e,f){for(;"[]"!==e.ctor;){a=b;f=c(e._0);for(var k=0;k<a.length;k++)a[k](f);e=e._1}return d});return{subscribe:function(a){b.push(a)},unsubscribe:function(a){b=b.slice();a=b.indexOf(a);0<=a&&b.splice(a,1)}}}function y(a,b){function c(a,b,c){k=b;return q}function d(a){for(var c=
k;"[]"!==c.ctor;)b(c._0(a)),c=c._1}var e=[],k=A.Nil,l=x[a].converter,h=function(a,b,f){a=c(a,b,f);for(b=0;b<e.length;b++)d(e[b]);e=null;g=d;h=c;return a},g=function(a){e.push(a)},q=z.succeed(null);x[a].init=q;x[a].onEffects=p(function(a,b,c){return h(a,b,c)});return{send:function(b){b=f(db,l,b);if("Err"===b.ctor)throw Error("Trying to send an unexpected type of value through port `"+a+"`:\n"+b._0);g(b._0)}}}var x={},B=e(function(a,b){return b}),C=e(function(a,b){return function(c){return a(b(c))}});
return{sendToApp:e(function(a,b){return z.nativeBinding(function(c){a.main(b);c(z.succeed(u.Tuple0))})}),sendToSelf:e(function(a,b){return f(z.send,a.self,{ctor:"self",_0:b})}),effectManagers:x,outgoingPort:function(a,b){k(a);x[a]={tag:"cmd",cmdMap:B,converter:b,isForeign:!0};return g(a)},incomingPort:function(a,b){k(a);x[a]={tag:"sub",subMap:C,converter:b,isForeign:!0};return g(a)},htmlToProgram:function(a){var b=n(A.Nil),c=u.Tuple2(u.Tuple0,b);return eb({init:c,view:function(a){return main},update:e(function(a,
b){return c}),subscriptions:function(a){return b}})},program:function(c){return function(d){return function(d,e){d.worker=function(d){if("undefined"!==typeof d)throw Error("The `"+e+"` module does not need flags.\nCall "+e+".worker() with no arguments and you should be all set!");return b(c.init,c.update,c.subscriptions,a)}}}},programWithFlags:function(c){return function(d){return function(e,k){e.worker=function(e){if("undefined"===typeof d)throw Error("Are you trying to sneak a Never value into Elm? Trickster!\nIt looks like "+
k+".main is defined with `programWithFlags` but has type `Program Never`.\nUse `program` instead if you do not want flags.");e=f(N.run,d,e);if("Err"===e.ctor)throw Error(k+".worker(...) was called with an unexpected argument.\nI tried to convert it to an Elm value, but ran into this problem:\n\n"+e._0);return b(c.init(e._0),c.update,c.subscriptions,a)}}}},initialize:b,leaf:g,batch:n,map:e(function(a,b){return{type:"map",tagger:a,tree:b}})}}(),z=function(){function a(a){return{ctor:"_Task_succeed",
value:a}}function b(a){return{ctor:"_Task_nativeBinding",callback:a,cancel:null}}function c(a){a={ctor:"_Process",id:u.guid(),root:a,stack:null,mailbox:[]};g(a);return a}function d(a,b){a.mailbox.push(b);g(a)}function f(a,b){for(;1E4>a;){var c=b.root.ctor;if("_Task_succeed"===c){for(;b.stack&&"_Task_onError"===b.stack.ctor;)b.stack=b.stack.rest;if(null===b.stack)break;b.root=b.stack.callback(b.root.value);b.stack=b.stack.rest;++a}else if("_Task_fail"===c){for(;b.stack&&"_Task_andThen"===b.stack.ctor;)b.stack=
b.stack.rest;if(null===b.stack)break;b.root=b.stack.callback(b.root.value);b.stack=b.stack.rest;++a}else if("_Task_andThen"===c)b.stack={ctor:"_Task_andThen",callback:b.root.callback,rest:b.stack},b.root=b.root.task,++a;else if("_Task_onError"===c)b.stack={ctor:"_Task_onError",callback:b.root.callback,rest:b.stack},b.root=b.root.task,++a;else{if("_Task_nativeBinding"===c){b.root.cancel=b.root.callback(function(a){b.root=a;g(b)});break}if("_Task_receive"===c){c=b.mailbox;if(0===c.length)break;b.root=
b.root.callback(c.shift());++a}else throw Error(c);}}if(1E4>a)return a+1;g(b);return a}function g(a){n.push(a);t||(setTimeout(p,0),t=!0)}function p(){for(var a=0,b;1E4>a&&(b=n.shift());)b.root&&(a=f(a,b));b?setTimeout(p,0):t=!1}var t=!1,n=[];return{succeed:a,fail:function(a){return{ctor:"_Task_fail",value:a}},nativeBinding:b,andThen:e(function(a,b){return{ctor:"_Task_andThen",callback:a,task:b}}),onError:e(function(a,b){return{ctor:"_Task_onError",callback:a,task:b}}),receive:function(a){return{ctor:"_Task_receive",
callback:a}},spawn:function(d){return b(function(b){var e=c(d);b(a(e))})},kill:function(c){return b(function(b){var d=c.root;"_Task_nativeBinding"===d.ctor&&d.cancel&&d.cancel();c.root=null;b(a(u.Tuple0))})},sleep:function(c){return b(function(b){var d=setTimeout(function(){b(a(u.Tuple0))},c);return function(){clearTimeout(d)}})},send:e(function(c,e){return b(function(b){d(c,e);b(a(u.Tuple0))})}),rawSpawn:c,rawSend:d}}(),fb=P.batch,Fa=fb({ctor:"[]"}),gb=gb||{};gb["!"]=e(function(a,b){return{ctor:"_Tuple2",
_0:a,_1:fb(b)}});var ac=P.batch,bc=ac({ctor:"[]"}),hb=P.sendToSelf,Ga=P.sendToApp,ib=z.onError,B=z.andThen,cc=e(function(a,b){return z.spawn(f(B,Ga(a),b._0))}),dc=z.fail;e(function(a,b){return f(ib,function(b){return dc(a(b))},b)});var C=z.succeed,Ha=e(function(a,b){return f(B,function(b){return C(a(b))},b)}),ec=p(function(a,b,c){return f(B,function(b){return f(B,function(c){return C(f(a,b,c))},c)},b)});y(function(a,b,c,d){return f(B,function(b){return f(B,function(c){return f(B,function(d){return C(r(a,
b,c,d))},d)},c)},b)});D(function(a,b,c,d,e){return f(B,function(b){return f(B,function(c){return f(B,function(d){return f(B,function(e){return C(T(a,b,c,d,e))},e)},d)},c)},b)});H(function(a,b,c,d,e,g){return f(B,function(b){return f(B,function(c){return f(B,function(d){return f(B,function(e){return f(B,function(f){return C(v(a,b,c,d,e,f))},g)},e)},d)},c)},b)});var wa=function(a){return"[]"===a.ctor?C({ctor:"[]"}):r(ec,e(function(a,c){return{ctor:"::",_0:a,_1:c}}),a._0,wa(a._1))},fc=p(function(a,b,
c){return f(Ha,function(a){return{ctor:"_Tuple0"}},wa(f(pa,cc(a),b)))}),gc=C({ctor:"_Tuple0"}),hc=p(function(a,b,c){return C({ctor:"_Tuple0"})}),jb=P.leaf("Task");e(function(a,b){return jb({ctor:"Perform",_0:f(Ha,a,b)})});e(function(a,b){return jb({ctor:"Perform",_0:f(ib,function(b){return C(a(x(b)))},f(B,function(b){return C(a(M(b)))},b))})});var ic=e(function(a,b){return{ctor:"Perform",_0:f(Ha,a,b._0)}});P.effectManagers.Task={pkg:"elm-lang/core",init:gc,onEffects:fc,onSelfMsg:hc,tag:"cmd",cmdMap:ic};
var kb=function(){return{now:z.nativeBinding(function(a){a(z.succeed(Date.now()))}),setInterval_:e(function(a,b){return z.nativeBinding(function(c){var d=setInterval(function(){z.rawSpawn(b)},a);return function(){clearInterval(d)}})})}}(),jc=kb.setInterval_,lb=p(function(a,b,c){if("[]"===b.ctor)return C(c);var d=b._0,e=z.spawn(f(jc,d,f(hb,a,d)));return f(B,function(e){return r(lb,a,b._1,r(S,d,e,c))},e)}),kc=e(function(a,b){var c=a._1;a=a._0;var d=f(Ba,a,b);return"Nothing"===d.ctor?r(S,a,{ctor:"::",
_0:c,_1:{ctor:"[]"}},b):r(S,a,{ctor:"::",_0:c,_1:d._0},b)}),lc=kb.now,mc=p(function(a,b,c){var d=f(Ba,b,c.taggers);return"Nothing"===d.ctor?C(c):f(B,function(a){return C(c)},f(B,function(b){return wa(f(pa,function(c){return f(Ga,a,c(b))},d._0))},lc))}),nc=P.leaf("Time"),mb=e(function(a,b){return{taggers:a,processes:b}}),oc=C(f(mb,R,R)),pc=p(function(a,b,c){var d=p(function(a,b,c){return{ctor:"_Tuple3",_0:c._0,_1:c._1,_2:f(B,function(a){return c._2},z.kill(b))}}),e=y(function(a,b,c,d){return{ctor:"_Tuple3",
_0:d._0,_1:r(S,a,c,d._1),_2:d._2}}),g=p(function(a,b,c){return{ctor:"_Tuple3",_0:{ctor:"::",_0:a,_1:c._0},_1:c._1,_2:c._2}}),n=r(ca,kc,R,b);b=tb(Lb,g,e,d,n,c.processes,{ctor:"_Tuple3",_0:{ctor:"[]"},_1:R,_2:C({ctor:"_Tuple0"})});var t=b._0,u=b._1;return f(B,function(a){return C(f(mb,n,a))},f(B,function(b){return r(lb,a,t,u)},b._2))}),nb=e(function(a,b){return{ctor:"Every",_0:a,_1:b}});e(function(a,b){return nc(f(nb,a,b))});var qc=e(function(a,b){return f(nb,b._0,function(c){return a(b._1(c))})});
P.effectManagers.Time={pkg:"elm-lang/core",init:oc,onEffects:pc,onSelfMsg:mc,tag:"sub",subMap:qc};var rc=z.kill,sc=z.spawn,tc=function(){function a(a){return function(b,c,d){return z.nativeBinding(function(e){function g(a){a=f(db,c,a);"Ok"===a.ctor&&z.rawSpawn(d(a._0))}a.addEventListener(b,g);return function(){a.removeEventListener(b,g)}})}}function b(a,b){return z.nativeBinding(function(c){g(function(){var d=document.getElementById(a);null===d?c(z.fail({ctor:"NotFound",_0:a})):c(z.succeed(b(d)))})})}
var c={addEventListener:function(){},removeEventListener:function(){}},d=a("undefined"!==typeof document?document:c);c=a("undefined"!==typeof window?window:c);var g="undefined"!==typeof requestAnimationFrame?requestAnimationFrame:function(a){a()};return{onDocument:p(d),onWindow:p(c),focus:function(a){return b(a,function(a){a.focus();return u.Tuple0})},blur:function(a){return b(a,function(a){a.blur();return u.Tuple0})},getScrollTop:function(a){return b(a,function(a){return a.scrollTop})},setScrollTop:e(function(a,
c){return b(a,function(a){a.scrollTop=c;return u.Tuple0})}),getScrollLeft:function(a){return b(a,function(a){return a.scrollLeft})},setScrollLeft:e(function(a,c){return b(a,function(a){a.scrollLeft=c;return u.Tuple0})}),toBottom:function(a){return b(a,function(a){a.scrollTop=a.scrollHeight;return u.Tuple0})},toRight:function(a){return b(a,function(a){a.scrollLeft=a.scrollWidth;return u.Tuple0})},height:e(function(a,c){return b(c,function(b){switch(a.ctor){case "Content":return b.scrollHeight;case "VisibleContent":return b.clientHeight;
case "VisibleContentWithBorders":return b.offsetHeight;case "VisibleContentWithBordersAndMargins":return b=b.getBoundingClientRect(),b.bottom-b.top}})}),width:e(function(a,c){return b(c,function(b){switch(a.ctor){case "Content":return b.scrollWidth;case "VisibleContent":return b.clientWidth;case "VisibleContentWithBorders":return b.offsetWidth;case "VisibleContentWithBordersAndMargins":return b=b.getBoundingClientRect(),b.right-b.left}})})}}().onWindow,da=function(){function a(a,b,c){return{type:"thunk",
func:a,args:b,thunk:c,node:void 0}}function b(a){for(var b,c={};"[]"!==a.ctor;){var d=a._0,e=d.key;if("ATTR"===e||"ATTR_NS"===e||"EVENT"===e){var m=c[e]||{};m[d.realKey]=d.value;c[e]=m}else if("STYLE"===e){m=c[e]||{};for(d=d.value;"[]"!==d.ctor;){var f=d._0;m[f._0]=f._1;d=d._1}c[e]=m}else"namespace"===e?b=d.value:"className"===e?(m=c[e],c[e]="undefined"===typeof m?d.value:m+" "+d.value):c[e]=d.value;a=a._1}return{facts:c,namespace:b}}function c(a,b,c){return{key:"EVENT",realKey:a,value:{options:b,
decoder:c}}}function d(a,b){switch(a.type){case "thunk":return a.node||(a.node=a.thunk()),d(a.node,b);case "tagger":var c=a.node;for(a=a.tagger;"tagger"===c.type;)"object"!==typeof a?a=[a,c.tagger]:a.push(c.tagger),c=c.node;b={tagger:a,parent:b};c=d(c,b);c.elm_event_node_ref=b;return c;case "text":return I.createTextNode(a.text);case "node":c=a.namespace?I.createElementNS(a.namespace,a.tag):I.createElement(a.tag);g(c,b,a.facts);a=a.children;for(var e=0;e<a.length;e++)c.appendChild(d(a[e],b));return c;
case "keyed-node":c=a.namespace?I.createElementNS(a.namespace,a.tag):I.createElement(a.tag);g(c,b,a.facts);a=a.children;for(e=0;e<a.length;e++)c.appendChild(d(a[e]._1,b));return c;case "custom":return c=a.impl.render(a.model),g(c,b,a.facts),c}}function g(a,b,c){for(var d in c){var e=c[d];switch(d){case "STYLE":var f=void 0,m=a.style;for(f in e)m[f]=e[f];break;case "EVENT":f=void 0;m=a;var w=b,g=e,Q=m.elm_handlers||{};for(f in g){e=Q[f];var k=g[f];"undefined"===typeof k?(m.removeEventListener(f,e),
Q[f]=void 0):"undefined"===typeof e?(e=n(w,k),m.addEventListener(f,e),Q[f]=e):e.info=k}m.elm_handlers=Q;break;case "ATTR":f=void 0;m=a;for(f in e)w=e[f],"undefined"===typeof w?m.removeAttribute(f):m.setAttribute(f,w);break;case "ATTR_NS":f=void 0;m=a;for(f in e)g=e[f],w=g.namespace,g=g.value,"undefined"===typeof g?m.removeAttributeNS(w,f):m.setAttributeNS(w,f,g);break;case "value":a[d]!==e&&(a[d]=e);break;default:a[d]=e}}}function n(a,b){function c(b){var d=c.info,e=f(N.run,d.decoder,b);if("Ok"===
e.ctor)for(d=d.options,d.stopPropagation&&b.stopPropagation(),d.preventDefault&&b.preventDefault(),b=e._0,e=a;e;){d=e.tagger;if("function"===typeof d)b=d(b);else for(var m=d.length;m--;)b=d[m](b);e=e.parent}}c.info=b;return c}function v(a,b){var c=[];x(a,b,c,0);return c}function t(a,b,c){return{index:b,type:a,data:c,domNode:void 0,eventNode:void 0}}function x(a,b,c,d){if(a!==b){var e=b.type;if(a.type!==e)c.push(t("p-redraw",d,b));else switch(e){case "thunk":for(var f=a.args,m=b.args,w=f.length,g=
a.func===b.func&&w===m.length;g&&w--;)g=f[w]===m[w];if(g){b.node=a.node;break}b.node=b.thunk();f=[];x(a.node,b.node,f,0);0<f.length&&c.push(t("p-thunk",d,f));break;case "tagger":g=a.tagger;f=b.tagger;var h=!1;for(m=a.node;"tagger"===m.type;)h=!0,"object"!==typeof g?g=[g,m.tagger]:g.push(m.tagger),m=m.node;for(w=b.node;"tagger"===w.type;)h=!0,"object"!==typeof f?f=[f,w.tagger]:f.push(w.tagger),w=w.node;if(h&&g.length!==f.length){c.push(t("p-redraw",d,b));break}if(h){a:{for(h=0;h<g.length;h++)if(g[h]!==
f[h]){g=!1;break a}g=!0}g=!g}else g=g!==f;g&&c.push(t("p-tagger",d,f));x(m,w,c,d+1);break;case "text":a.text!==b.text&&c.push(t("p-text",d,b.text));break;case "node":if(a.tag!==b.tag||a.namespace!==b.namespace){c.push(t("p-redraw",d,b));break}e=l(a.facts,b.facts);"undefined"!==typeof e&&c.push(t("p-facts",d,e));f=a.children;m=b.children;w=f.length;g=m.length;w>g?c.push(t("p-remove-last",d,w-g)):w<g&&c.push(t("p-append",d,m.slice(w)));w=w<g?w:g;for(g=0;g<w;g++)d++,h=f[g],x(h,m[g],c,d),d+=h.descendantsCount||
0;break;case "keyed-node":if(a.tag!==b.tag||a.namespace!==b.namespace){c.push(t("p-redraw",d,b));break}e=l(a.facts,b.facts);"undefined"!==typeof e&&c.push(t("p-facts",d,e));e=[];var Q={},ia=[];a=a.children;for(var n=b.children,p=a.length,u=n.length,q=0,r=0,v=d;q<p&&r<u;){var y=a[q];var z=n[r];var A=y._0,C=z._0;b=y._1;z=z._1;if(A===C)v++,x(b,z,e,v),v+=b.descendantsCount||0,q++,r++;else{y=q+1<p;var E=r+1<u;if(y){var D=a[q+1];m=D._0;var F=D._1;D=C===m}E&&(g=n[r+1],f=g._0,h=g._1,g=A===f);if(y&&E&&g&&
D)v++,x(b,h,e,v),k(Q,e,A,z,r,ia),v+=b.descendantsCount||0,v++,B(Q,e,A,F,v),v+=F.descendantsCount||0,q+=2,r+=2;else if(E&&g)v++,k(Q,e,C,z,r,ia),x(b,h,e,v),v+=b.descendantsCount||0,q+=1,r+=2;else if(y&&D)v++,B(Q,e,A,b,v),v+=b.descendantsCount||0,v++,x(F,z,e,v),v+=F.descendantsCount||0,q+=2,r+=1;else if(y&&E&&m===f)v++,B(Q,e,A,b,v),k(Q,e,C,z,r,ia),v+=b.descendantsCount||0,v++,x(F,h,e,v),v+=F.descendantsCount||0,q+=2,r+=2;else break}}for(;q<p;)v++,y=a[q],b=y._1,B(Q,e,y._0,b,v),v+=b.descendantsCount||
0,q++;for(;r<u;)w=w||[],z=n[r],k(Q,e,z._0,z._1,void 0,w),r++;(0<e.length||0<ia.length||"undefined"!==typeof w)&&c.push(t("p-reorder",d,{patches:e,inserts:ia,endInserts:w}));break;case "custom":a.impl!==b.impl?c.push(t("p-redraw",d,b)):(e=l(a.facts,b.facts),"undefined"!==typeof e&&c.push(t("p-facts",d,e)),(f=b.impl.diff(a,b))&&c.push(t("p-custom",d,f)))}}}function l(a,b,c){var d;for(d in a)if("STYLE"===d||"EVENT"===d||"ATTR"===d||"ATTR_NS"===d){var e=l(a[d],b[d]||{},d);if(e){var f=f||{};f[d]=e}}else if(d in
b){e=a[d];var m=b[d],g;!(g=e===m&&"value"!==d)&&(g="EVENT"===c)&&(g=e.options===m.options||e.options.stopPropagation===m.options.stopPropagation&&e.options.preventDefault===m.options.preventDefault?N.equality(e.decoder,m.decoder):!1);g||(f=f||{},f[d]=m)}else f=f||{},f[d]="undefined"===typeof c?"string"===typeof a[d]?"":null:"STYLE"===c?"":"EVENT"===c||"ATTR"===c?void 0:{namespace:a[d].namespace,value:void 0};for(var w in b)w in a||(f=f||{},f[w]=b[w]);return f}function k(a,b,c,d,e,f){var m=a[c];"undefined"===
typeof m?(m={tag:"insert",vnode:d,index:e,data:void 0},f.push({index:e,entry:m}),a[c]=m):"remove"===m.tag?(f.push({index:e,entry:m}),m.tag="move",a=[],x(m.vnode,d,a,m.index),m.index=e,m.data.data={patches:a,entry:m}):k(a,b,c+X,d,e,f)}function B(a,b,c,d,e){var f=a[c];"undefined"===typeof f?(f=t("p-remove",e,void 0),b.push(f),a[c]={tag:"remove",vnode:d,index:e,data:f}):"insert"===f.tag?(f.tag="move",a=[],x(d,f.vnode,a,e),f=t("p-remove",e,{patches:a,entry:f}),b.push(f)):B(a,b,c+X,d,e)}function A(a,b,
c,d,e,f,g){for(var m,w=c[d],h=w.index;h===e;)if(m=w.type,"p-thunk"===m?(m=b.node,A(a,m,w.data,0,0,m.descendantsCount,g)):"p-reorder"===m?(w.domNode=a,w.eventNode=g,m=w.data.patches,0<m.length&&A(a,b,m,0,e,f,g)):"p-remove"===m?(w.domNode=a,w.eventNode=g,m=w.data,"undefined"!==typeof m&&(m.entry.data=a,m=m.patches,0<m.length&&A(a,b,m,0,e,f,g))):(w.domNode=a,w.eventNode=g),d++,!(w=c[d])||(h=w.index)>f)return d;switch(b.type){case "tagger":for(g=b.node;"tagger"===g.type;)g=g.node;return A(a,g,c,d,e+1,
f,a.elm_event_node_ref);case "node":b=b.children;for(var k=a.childNodes,l=0;l<b.length;l++){e++;m=b[l];a=e+(m.descendantsCount||0);if(e<=h&&h<=a&&(d=A(k[l],m,c,d,e,a,g),!(w=c[d])||(h=w.index)>f))break;e=a}return d;case "keyed-node":b=b.children;k=a.childNodes;for(l=0;l<b.length;l++){e++;m=b[l]._1;a=e+(m.descendantsCount||0);if(e<=h&&h<=a&&(d=A(k[l],m,c,d,e,a,g),!(w=c[d])||(h=w.index)>f))break;e=a}return d;case "text":case "thunk":throw Error("should never traverse `text` or `thunk` nodes like this");
}}function C(a,b,c,d){if(0===c.length)return a;A(a,b,c,0,0,b.descendantsCount,d);return D(a,c)}function D(a,b){for(var c=0;c<b.length;c++){var d=b[c],e=d.domNode;d=G(e,d);e===a&&(a=d)}return a}function G(a,b){switch(b.type){case "p-redraw":var c=a.parentNode;b=d(b.data,b.eventNode);"undefined"===typeof b.elm_event_node_ref&&(b.elm_event_node_ref=a.elm_event_node_ref);c&&b!==a&&c.replaceChild(b,a);return b;case "p-facts":return g(a,b.eventNode,b.data),a;case "p-text":return a.replaceData(0,a.length,
b.data),a;case "p-thunk":return D(a,b.data);case "p-tagger":return"undefined"!==typeof a.elm_event_node_ref?a.elm_event_node_ref.tagger=b.data:a.elm_event_node_ref={tagger:b.data,parent:b.eventNode},a;case "p-remove-last":for(c=b.data;c--;)a.removeChild(a.lastChild);return a;case "p-append":var e=b.data;for(c=0;c<e.length;c++)a.appendChild(d(e[c],b.eventNode));return a;case "p-remove":b=b.data;if("undefined"===typeof b)return a.parentNode.removeChild(a),a;c=b.entry;"undefined"!==typeof c.index&&a.parentNode.removeChild(a);
c.data=D(a,b.patches);return a;case "p-reorder":e=b.data;c=e.endInserts;if("undefined"!==typeof c){for(var f=I.createDocumentFragment(),m=0;m<c.length;m++){var h=c[m].entry;f.appendChild("move"===h.tag?h.data:d(h.vnode,b.eventNode))}c=f}else c=void 0;a=D(a,e.patches);e=e.inserts;for(f=0;f<e.length;f++)m=e[f],h=m.entry,h="move"===h.tag?h.data:d(h.vnode,b.eventNode),a.insertBefore(h,a.childNodes[m.index]);"undefined"!==typeof c&&a.appendChild(c);return a;case "p-custom":return b=b.data,b.applyPatch(a,
b.data);default:throw Error("Ran into an unknown patch!");}}function F(a){return e(function(b,c){return function(d){return function(e,g,m){var h=a(d,g);"undefined"===typeof m?K(c,e,g,h):E(f(b,m,c),e,g,h)}}})}function H(a,b){b&&(b.innerHTML='<div style="padding-left:1em;"><h2 style="font-weight:normal;"><b>Oops!</b> Something went wrong when starting your Elm program.</h2><pre style="padding-left:1em;">'+a+"</pre></div>");throw Error(a);}function K(a,b,c,d){b.embed=function(b,c){for(;b.lastChild;)b.removeChild(b.lastChild);
return P.initialize(d(a.init,c,b),a.update,a.subscriptions,J(b,a.view))};b.fullscreen=function(b){return P.initialize(d(a.init,b,document.body),a.update,a.subscriptions,J(document.body,a.view))}}function J(a,b){return function(c,e){c={tagger:c,parent:void 0};e=b(e);var f=d(e,c);a.appendChild(f);return L(f,b,e,c)}}function L(a,b,c,d){function e(){switch(f){case "NO_REQUEST":throw Error("Unexpected draw callback.\nPlease report this to <https://github.com/elm-lang/virtual-dom/issues>.");case "PENDING_REQUEST":Z(e);
f="EXTRA_REQUEST";var c=b(m),h=v(g,c);a=C(a,g,h,d);g=c;break;case "EXTRA_REQUEST":f="NO_REQUEST"}}var f="NO_REQUEST",g=c,m;return function(a){"NO_REQUEST"===f&&Z(e);f="PENDING_REQUEST";m=a}}function E(a,b,c,d){b.fullscreen=function(b){var e={doc:void 0};return P.initialize(d(a.init,b,document.body),a.update(M(e)),a.subscriptions,O(c,document.body,e,a.view,a.viewIn,a.viewOut))};b.embed=function(b,e){var f={doc:void 0};return P.initialize(d(a.init,e,b),a.update(M(f)),a.subscriptions,O(c,b,f,a.view,
a.viewIn,a.viewOut))}}function M(a){return z.nativeBinding(function(b){var c=a.doc;c&&(c=c.getElementsByClassName("debugger-sidebar-messages")[0])&&(c.scrollTop=c.scrollHeight);b(z.succeed(u.Tuple0))})}function O(a,b,c,e,f,g){return function(h,m){var k={tagger:h,parent:void 0};h={tagger:h,parent:void 0};var l=e(m),w=d(l,k);b.appendChild(w);var n=L(w,e,l,k);l=f(m)._1;w=d(l,h);b.appendChild(w);k=U(k,w,f);var p=L(w,k,l,h),q=R(m,g,h,b,a,c);return function(a){n(a);p(a);q(a)}}}function R(a,b,c,d,e,f){var g,
h;return function(a){if(a.isDebuggerOpen)if(f.doc){I=f.doc;a=b(a);var d=v(g,a);h=C(h,g,d,c);g=a;I=document}else g=b(a),h=T(e,f,g,c)}}function T(a,b,c,e){function f(){b.doc=void 0;g.close()}var g=window.open("","","width=900,height=360,left="+(screen.width-900)+",top="+(screen.height-360));I=g.document;b.doc=I;I.title="Debugger - "+a;I.body.style.margin="0";I.body.style.padding="0";a=d(c,e);I.body.appendChild(a);I.addEventListener("keydown",function(a){a.metaKey&&82===a.which&&window.location.reload();
38===a.which&&(e.tagger({ctor:"Up"}),a.preventDefault());40===a.which&&(e.tagger({ctor:"Down"}),a.preventDefault())});window.addEventListener("unload",f);g.addEventListener("unload",function(){b.doc=void 0;window.removeEventListener("unload",f);e.tagger({ctor:"Close"})});I=document;return a}function U(a,b,c){var d=W(b),e="Normal",f,g=a.tagger,h=function(){};return function(b){b=c(b);var m=b._0.ctor;a.tagger="Normal"===m?g:h;e!==m&&(S("removeEventListener",d,e),S("addEventListener",d,m),"Normal"===
e&&(f=document.body.style.overflow,document.body.style.overflow="hidden"),"Normal"===m&&(document.body.style.overflow=f),e=m);return b._1}}function S(a,b,c){switch(c){case "Pause":return V(a,b,ca);case "Message":return V(a,b,fa)}}function V(a,b,c){for(var d=0;d<c.length;d++)document.body[a](c[d],b,!0)}function W(a){return function(b){if("keydown"!==b.type||!b.metaKey||82!==b.which){for(var c="scroll"===b.type||"wheel"===b.type,d=b.target;null!==d;){if("elm-overlay-message-details"===d.className&&
c||d===a&&!c)return;d=d.parentNode}b.stopPropagation();b.preventDefault()}}}var I="undefined"!==typeof document?document:{},X="_elmW6BL",Y=F(function(a,b){return function(a,c,d){if("undefined"===typeof c)return a;H("The `"+b+"` module does not need flags.\nInitialize it with no arguments and you should be all set!",d)}}),da=F(function(a,b){return function(c,d,e){if("undefined"===typeof a){var g="Are you trying to sneak a Never value into Elm? Trickster!\nIt looks like "+b+".main is defined with `programWithFlags` but has type `Program Never`.\nUse `program` instead if you do not want flags.";
H(g,e)}d=f(N.run,a,d);if("Ok"===d.ctor)return c(d._0);g="Trying to initialize the `"+b+"` module with an unexpected flag.\nI tried to convert it to an Elm value, but ran into this problem:\n\n"+d._0;H(g,e)}}),Z="undefined"!==typeof requestAnimationFrame?requestAnimationFrame:function(a){setTimeout(a,1E3/60)},ca="click dblclick mousemove mouseup mousedown mouseenter mouseleave touchstart touchend touchcancel touchmove pointerdown pointerup pointerover pointerout pointerenter pointerleave pointermove pointercancel dragstart drag dragend dragenter dragover dragleave drop keyup keydown keypress input change focus blur".split(" "),
fa=ca.concat("wheel","scroll");return{node:function(a){return e(function(c,d){var e=b(c);c=e.namespace;e=e.facts;for(var f=[],g=0;"[]"!==d.ctor;){var h=d._0;g+=h.descendantsCount||0;f.push(h);d=d._1}g+=f.length;return{type:"node",tag:a,facts:e,children:f,namespace:c,descendantsCount:g}})},text:function(a){return{type:"text",text:a}},custom:function(a,c,d){return{type:"custom",facts:b(a).facts,model:c,impl:d}},map:e(function(a,b){return{type:"tagger",tagger:a,node:b,descendantsCount:1+(b.descendantsCount||
0)}}),on:p(c),style:function(a){return{key:"STYLE",value:a}},property:e(function(a,b){return{key:a,value:b}}),attribute:e(function(a,b){return{key:"ATTR",realKey:a,value:b}}),attributeNS:p(function(a,b,c){return{key:"ATTR_NS",realKey:b,value:{value:c,namespace:a}}}),mapProperty:e(function(a,b){return"EVENT"!==b.key?b:c(b.realKey,b.value.options,f($b,a,b.value.decoder))}),lazy:e(function(b,c){return a(b,[c],function(){return b(c)})}),lazy2:p(function(b,c,d){return a(b,[c,d],function(){return f(b,c,
d)})}),lazy3:y(function(b,c,d,e){return a(b,[c,d,e],function(){return r(b,c,d,e)})}),keyedNode:p(function(a,c,d){var e=b(c);c=e.namespace;e=e.facts;for(var f=[],g=0;"[]"!==d.ctor;){var h=d._0;g+=h._1.descendantsCount||0;f.push(h);d=d._1}g+=f.length;return{type:"keyed-node",tag:a,facts:e,children:f,namespace:c,descendantsCount:g}}),program:Y,programWithFlags:da,staticProgram:function(a){var b=u.Tuple2(u.Tuple0,Fa);return f(Y,void 0,{init:b,view:function(){return a},update:e(function(){return b}),subscriptions:function(){return bc}})()}}}(),
eb=function(a){return f(da.program,void 0,a)},uc={stopPropagation:!1,preventDefault:!1},vc=da.on;e(function(a,b){return r(vc,a,uc,b)});var ob=da.style,pb=da.property,wc=da.text,g=da.node;e(function(a,b){return{stopPropagation:a,preventDefault:b}});var xc=eb;g("body");g("section");g("nav");g("article");g("aside");g("h1");g("h2");g("h3");g("h4");g("h5");g("h6");g("header");g("footer");g("address");g("main");g("p");g("hr");g("pre");g("blockquote");g("ol");g("ul");g("li");g("dl");g("dt");g("dd");g("figure");
g("figcaption");var qb=g("div");g("a");g("em");g("strong");g("small");g("s");g("cite");g("q");g("dfn");g("abbr");g("time");g("code");g("var");g("samp");g("kbd");g("sub");g("sup");g("i");g("b");g("u");g("mark");g("ruby");g("rt");g("rp");g("bdi");g("bdo");g("span");g("br");g("wbr");g("ins");g("del");g("img");g("iframe");g("embed");g("object");g("param");g("video");g("audio");g("source");g("track");g("canvas");g("math");g("table");g("caption");g("colgroup");g("col");g("tbody");g("thead");g("tfoot");
g("tr");g("td");g("th");g("form");g("fieldset");g("legend");g("label");g("input");g("button");g("select");g("datalist");g("optgroup");g("option");g("textarea");g("keygen");g("output");g("progress");g("meter");g("details");g("summary");g("menuitem");g("menu");e(function(a,b){return f(pb,a,Yb(b))});e(function(a,b){return f(pb,a,Xb(b))});var xa=xa||{};xa["&>"]=e(function(a,b){return f(B,oa(b),a)});var yc=p(function(a,b,c){return"Nothing"===c.ctor?C(c):f(xa["&>"],wa(f(pa,function(c){return f(Ga,a,c._0(b))},
c._0.subs)),C(c))}),zc=C(K),Ac=P.leaf("Device.Orientation"),Bc=p(function(a,b,c){return{alpha:a,beta:b,gamma:c}}),Cc=T(Zb,Bc,f(va,"alpha",Ea),f(va,"beta",Ea),f(va,"gamma",Ea)),Dc=p(function(a,b,c){if("Nothing"===c.ctor){if("[]"===b.ctor)return C(K);a=hb(a);a=r(tc,"deviceorientation",Cc,a);return f(B,function(a){return C(L({subs:b,pid:a}))},sc(a))}return"[]"===b.ctor?f(xa["&>"],rc(c._0.pid),C(K)):C(L({subs:b,pid:c._0.pid}))}),Ec=e(function(a,b){return{ctor:"MySub",_0:function(c){return a(b._0(c))}}});
P.effectManagers["Device.Orientation"]={pkg:"sch/elm-device-examples",init:zc,onEffects:Dc,onSelfMsg:yc,tag:"sub",subMap:Ec};var Fc=e(function(a,b){return{ctor:"_Tuple2",_0:a._0,_1:Fa}}),Gc=function(a){return{ctor:"Reorient",_0:a}},rb=xc({init:{ctor:"_Tuple2",_0:{alpha:0,beta:0,gamma:0},_1:Fa},update:Fc,view:function(a){var b=f(n["++"],"rotateY(",f(n["++"],U(yb(a.gamma)/3),"deg)")),c=f(n["++"],"rotateX(",f(n["++"],U(r(xb,-90,90,a.beta)/3),"deg)")),d=f(n["++"],"rotateZ(",f(n["++"],U(a.alpha),"deg)"));
b={ctor:"::",_0:{ctor:"_Tuple2",_0:"padding",_1:"0.618em"},_1:{ctor:"::",_0:{ctor:"_Tuple2",_0:"font-family",_1:"-apple-system, BlinkMacSystemFont, sans-serif"},_1:{ctor:"::",_0:{ctor:"_Tuple2",_0:"font-size",_1:"200%"},_1:{ctor:"::",_0:{ctor:"_Tuple2",_0:"font-weight",_1:"500"},_1:{ctor:"::",_0:{ctor:"_Tuple2",_0:"color",_1:"white"},_1:{ctor:"::",_0:{ctor:"_Tuple2",_0:"transform",_1:f(n["++"],"perspective(500px) ",f(n["++"],c,f(n["++"]," ",f(n["++"],b,f(n["++"]," ",d)))))},_1:{ctor:"::",_0:{ctor:"_Tuple2",
_0:"background-color",_1:"rgba(255, 255, 255, 0.1)"},_1:{ctor:"::",_0:{ctor:"_Tuple2",_0:"box-shadow",_1:"0 1px 3px rgba(1, 1, 1, 0.1)"},_1:{ctor:"::",_0:{ctor:"_Tuple2",_0:"border-radius",_1:"3px"},_1:{ctor:"::",_0:{ctor:"_Tuple2",_0:"min-width",_1:"2.2em"},_1:{ctor:"::",_0:{ctor:"_Tuple2",_0:"text-align",_1:"right"},_1:{ctor:"[]"}}}}}}}}}}}};a=f(n["++"],U(wb(a.alpha)),"\u00b0");a=f(qb,{ctor:"::",_0:ob(b),_1:{ctor:"[]"}},{ctor:"::",_0:wc(a),_1:{ctor:"[]"}});return f(qb,{ctor:"::",_0:ob({ctor:"::",
_0:{ctor:"_Tuple2",_0:"position",_1:"absolute"},_1:{ctor:"::",_0:{ctor:"_Tuple2",_0:"top",_1:"0"},_1:{ctor:"::",_0:{ctor:"_Tuple2",_0:"bottom",_1:"0"},_1:{ctor:"::",_0:{ctor:"_Tuple2",_0:"left",_1:"0"},_1:{ctor:"::",_0:{ctor:"_Tuple2",_0:"right",_1:"0"},_1:{ctor:"::",_0:{ctor:"_Tuple2",_0:"display",_1:"flex"},_1:{ctor:"::",_0:{ctor:"_Tuple2",_0:"align-items",_1:"center"},_1:{ctor:"::",_0:{ctor:"_Tuple2",_0:"justify-content",_1:"center"},_1:{ctor:"::",_0:{ctor:"_Tuple2",_0:"background-color",_1:"#60B5CC"},
_1:{ctor:"[]"}}}}}}}}}}),_1:{ctor:"[]"}},{ctor:"::",_0:a,_1:{ctor:"[]"}})},subscriptions:function(a){return Ac({ctor:"MySub",_0:Gc})}})(),W={};W.ScreenRotationExample=W.ScreenRotationExample||{};"undefined"!==typeof rb&&rb(W.ScreenRotationExample,"ScreenRotationExample",void 0);if("function"===typeof define&&define.amd)define([],function(){return W});else if("object"===typeof module)module.exports=W;else{var Ia=this.Elm;if("undefined"===typeof Ia)this.Elm=W;else for(var ya in W){if(ya in Ia)throw Error("There are two Elm modules called `"+
ya+"` on this page! Rename one of them.");Ia[ya]=W[ya]}}}).call(this);
