#!/bin/bash

# script/publish-examples: Build examples and upload to github pages

set -e

cd "$(dirname "$0")/../examples"

elm-make ScreenRotationExample.elm --output ../build/index.html
elm-make PlotAccelerationExample.elm --output ../build/acceleration/index.html
cd ..
VIEWPORT='<meta name="viewport" content="width=device-width, initial-scale=1"><style>'
sed -i '' "s|</title><style>|</title>$VIEWPORT<style>|" build/index.html
sed -i '' "s|</title><style>|</title>$VIEWPORT<style>|" build/acceleration/index.html

TEMPORARY_DIRECTORY=`mktemp -d`
cp -r build/. $TEMPORARY_DIRECTORY
cd $TEMPORARY_DIRECTORY

git init
git add .
git commit -m "Rebuilt examples website"
git remote add origin git@github.com:sch/elm-device.git
git push origin HEAD:gh-pages --force
